/* v20 - final publishable controls and spreadsheet-reference safeguards. */
(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var $$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));};
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
function st(){try{return window.mortgageSuite&&window.mortgageSuite.store;}catch(e){return null;}}
function say(a,b,k){if(window.LOS&&LOS.say)LOS.say(a,b,k||'good',6500);else if(window.toast)toast(a+(b?' - '+b:''));}
function money(v){var n=Number(v)||0;return(n<0?'-':'')+'$'+Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}
var V=window.V20={version:'20.0'};
function supportedProperty(i,o){var maxPay=Number(o&&o.aus&&o.aus.maxSupportedHousingPayment)||0,p=o&&o.payment||{},mi=Number(o&&o.isFha?p.monthlyFhaMip:p.monthlyPmi)||0,other=Number(p.monthlyTaxes||0)+Number(p.monthlyInsurance||0)+Number(p.hoaMonthly||0),pi=Math.max(0,maxPay-other-mi),rate=Number(i&&i.interestRate||0)/12,n=Math.max(1,Math.round(Number(i&&i.termYears||30)*12)),loan=rate?pi*(1-Math.pow(1+rate,-n))/rate:pi*n;return loan/Math.max(.01,1-Number(i&&i.finalDownPaymentPct||0));}

V.parseNumber=function(raw){var s=String(raw==null?'':raw).trim();if(!s)return{ok:false,blank:true,value:null};var neg=/^\(.*\)$/.test(s),pct=/%$/.test(s);s=s.replace(/[()$,%\s]/g,'').replace(/,/g,'');var m=s.match(/^(-?(?:\d+\.?\d*|\.\d+))([km])?$/i);if(!m)return{ok:false,blank:false,value:null};var n=parseFloat(m[1]),mult=!m[2]?1:m[2].toLowerCase()==='k'?1000:1000000;n=(neg?-Math.abs(n):n)*mult;return{ok:isFinite(n),blank:false,value:n,pct:pct};};
V.reference203k=function(x){x=x||{};var price=Number(x.purchase)||0,asis=Number(x.asIs)||0,rehab=Number(x.rehab)||0,arv=Number(x.arv)||0,dp=Number(x.downPct==null ? .035 : x.downPct),limit=Number(x.fhaLimit)||Infinity,energy=Number(x.energy)||0,uf=Number(x.ufmipRate==null ? .0175 : x.ufmipRate),c1=Math.min(price,asis||price),c3=Math.min(c1+rehab,arv?arv*1.10:Infinity),msi=c3*dp,baseBefore=c3*(1-dp)+energy,base=Math.min(baseBefore,limit),ufmip=base*uf;return{c1:c1,c3:c3,minimumInvestment:msi,baseBeforeLimit:baseBefore,maximumBaseLoan:base,ufmip:ufmip,totalLoan:base+ufmip};};

function pathGet(obj,path){return String(path).split('.').reduce(function(a,k){return a==null?undefined:a[k];},obj);}
function pathSet(obj,path,val){var p=String(path).split('.'),t=obj;for(var i=0;i<p.length-1;i++){if(!t[p[i]]||typeof t[p[i]]!=='object')t[p[i]]={};t=t[p[i]];}t[p[p.length-1]]=val;}
function numValue(raw,pct,allowBlank){var p=V.parseNumber(raw);if(p.blank&&allowBlank)return{ok:true,value:null};if(!p.ok)return p;return{ok:true,value:pct?p.value/100:p.value};}
V.setScenario=function(path,raw,kind){var store=st();if(!store)return false;var p=kind==='pct'?numValue(raw,true,false):kind==='num'?numValue(raw,false,false):kind==='bool'?{ok:true,value:raw===true||String(raw)==='true'||String(raw)==='yes'}:{ok:true,value:raw};if(!p.ok){say('Value not changed','Enter a number such as 500000, $500,000, 500k, or 3.5%.','warn');return false;}store.setField(path,p.value,'Direct edit');var i=store.activeInputs;if(path==='asIsValue')i.v20ValueAuto=false;if(path==='basePurchasePrice'&&(i.v20ValueAuto||!Number(i.asIsValue))){i.asIsValue=p.value;i.v20ValueAuto=true;}if(path==='reno.baseCost'&&!Number(p.value)){i.renovation=false;i.renovationScope='Auto';}if(path==='renovation'&&p.value&&!Number(i.reno.baseCost))i.reno.baseCost=50000;if(path==='mortgagePaymentsEscrowed'&&!p.value)i.reno.paymentReserveMonths=0;store.emit();return true;};

V.compareSet=function(id,path,raw,kind){var store=st(),s=store&&store.snapshot.scenarios[id];if(!s)return;var p=kind==='pct'?numValue(raw,true,false):kind==='num'?numValue(raw,false,false):{ok:true,value:raw};if(!p.ok)return say('Scenario value not changed','Enter a valid freeform number.','warn');pathSet(s.inputs,path,p.value);if(path==='asIsValue')s.inputs.v20ValueAuto=false;if(path==='basePurchasePrice'&&(s.inputs.v20ValueAuto||!Number(s.inputs.asIsValue))){s.inputs.asIsValue=p.value;s.inputs.v20ValueAuto=true;}if(path==='reno.baseCost'&&!Number(p.value)){s.inputs.renovation=false;s.inputs.renovationScope='Auto';}s.updatedAt=new Date().toISOString();store.emit();if(window.V17)V17.renderCompare();};
function compareColumns(){var table=document.querySelector('#v14CompareBody .v17-comparison');if(!table||table.dataset.v20)return;table.dataset.v20='1';var head=table.tHead&&table.tHead.rows[0],price=head&&Array.prototype.find.call(head.cells,function(c){return c.textContent.trim()==='Price';});if(!price)return;['As-is value','ARV','Max property value','MMW base loan'].forEach(function(label){var th=document.createElement('th');th.textContent=label;price.parentNode.insertBefore(th,price.nextSibling);price=th;});Array.prototype.forEach.call(table.tBodies[0].rows,function(tr){var first=tr.cells[0]&&tr.cells[0].querySelector('input'),m=first&&String(first.getAttribute('onchange')||'').match(/compareSet\('([^']+)'/),id=m&&m[1],store=st(),s=id&&store&&store.snapshot.scenarios[id],i=s&&s.inputs,o=id&&store&&store.outputsFor(id),cap=window.V7&&V7.capacity?V7.capacity():null,maxProperty=cap&&cap.maxLoan?cap.maxLoan/Math.max(.01,1-Number(i&&i.finalDownPaymentPct||0)):0,anchor=tr.cells[7];if(!s||!anchor)return;var cells=[['asIsValue',i.asIsValue],['afterRepairValue',i.afterRepairValue]];cells.forEach(function(x){var td=document.createElement('td');td.innerHTML='<input class="cell-input money" inputmode="decimal" value="'+esc(x[1]||'')+'" onchange="V20.compareSet(\''+esc(id)+'\',\''+x[0]+'\',this.value,\'num\')">';anchor.parentNode.insertBefore(td,anchor.nextSibling);anchor=td;});var td1=document.createElement('td');td1.textContent=maxProperty?money(maxProperty):'—';anchor.parentNode.insertBefore(td1,anchor.nextSibling);anchor=td1;var td2=document.createElement('td');td2.textContent=money(o.loan.maximumBaseLoan);anchor.parentNode.insertBefore(td2,anchor.nextSibling);});}

function validateCapture(e){var el=e.target;if(!el||el.tagName!=='INPUT'||!(el.dataset.v19Freeform||el.inputMode==='decimal'))return;if(e.type==='focusin'){el.dataset.v20LastValid=el.value;return;}if(e.type!=='change'&&e.type!=='focusout')return;var p=V.parseNumber(el.value),blank=p.blank&&!el.dataset.v20Required;if(p.ok||blank){el.classList.remove('v20-invalid');el.removeAttribute('aria-invalid');el.setCustomValidity('');el.dataset.v20LastValid=el.value;return;}e.preventDefault();e.stopImmediatePropagation();el.classList.add('v20-invalid');el.setAttribute('aria-invalid','true');el.setCustomValidity('Enter a valid number');say('Invalid number','The previous value was kept. Use digits, commas, $, %, k, or m.','warn');el.value=el.dataset.v20LastValid||'';}
document.addEventListener('focusin',validateCapture,true);document.addEventListener('change',validateCapture,true);document.addEventListener('focusout',validateCapture,true);

function normalizeScenarioRules(){var store=st(),changed=false;if(!store)return;Object.keys(store.snapshot.scenarios||{}).forEach(function(id){var i=store.snapshot.scenarios[id].inputs;if(!i)return;if(!i.v20Initialized){i.v20Initialized=true;if(!Number(i.basePurchasePrice))i.basePurchasePrice=500000;if(!Number(i.asIsValue)){i.asIsValue=Number(i.basePurchasePrice);i.v20ValueAuto=true;}if(i.loanProgram==='FHA'&&!Number(i.finalDownPaymentPct))i.finalDownPaymentPct=.035;if(i.renovation&&!Number(i.reno&&i.reno.baseCost))i.reno.baseCost=50000;if(i.escrow&&Number(i.escrow.cushionMonthsOverride)<0)i.escrow.cushionMonthsOverride=2;if(i.mortgagePaymentsEscrowed==null)i.mortgagePaymentsEscrowed=true;changed=true;}if(i.v20ValueAuto&&Number(i.asIsValue)!==Number(i.basePurchasePrice)){i.asIsValue=Number(i.basePurchasePrice);changed=true;}if(i.renovation&&i.reno&&!Number(i.reno.baseCost)&&i.v20RenoWasPositive){i.renovation=false;i.renovationScope='Auto';changed=true;}if(i.reno&&Number(i.reno.baseCost)>0)i.v20RenoWasPositive=true;});if(changed)store.emit();}
function ensureOutputAliases(){var store=st(),o=store&&store.outputs;if(o&&o.value&&o.loan)o.value.valueBasis=o.loan.valueBasis;}

function f(label,path,val,kind,wide){return'<div class="v20-field '+(wide?'wide':'')+'"><label>'+label+'</label><input class="cell-input" inputmode="'+(kind==='text'?'text':'decimal')+'" value="'+esc(val==null?'':val)+'" onchange="V20.setScenario(\''+path+'\',this.value,\''+(kind||'text')+'\');V20.renderSetup()"></div>';}
V.renderSetup=function(){var store=st(),body=$('screen-body');if(!store||store.snapshot.mode!=='setup'||!body)return;var i=store.activeInputs,o=store.outputs,old=$('v20Setup');if(old)old.remove();var d=document.createElement('div');d.id='v20Setup';d.className='card v20-setup';d.innerHTML='<h3>Scenario control center</h3><div class="body"><div class="v20-grid">'+f('Borrower name','borrowerName',i.borrowerName,'text',true)+f('Property address','propertyAddress',i.propertyAddress,'text',true)+f('ZIP code','zipCode',i.zipCode,'text')+f('State','state',i.state,'text')+f('County / area','nyCounty',i.nyCounty,'text')+f('Purchase price','basePurchasePrice',i.basePurchasePrice,'num')+f('As-is value','asIsValue',i.asIsValue,'num')+f('After-repair value','afterRepairValue',i.afterRepairValue,'num')+f('Down payment %','finalDownPaymentPct',(Number(i.finalDownPaymentPct)*100).toFixed(3),'pct')+f('Renovation budget','reno.baseCost',i.reno&&i.reno.baseCost,'num')+'</div><div class="v20-quick"><button class="btn small" onclick="V20.setScenario(\'finalDownPaymentPct\',\'3.5\',\'pct\');V20.renderSetup()">FHA 3.5%</button><button class="btn small ghost" onclick="V20.setScenario(\'finalDownPaymentPct\',\'5\',\'pct\');V20.renderSetup()">5% down</button><button class="btn small ghost" onclick="mortgageSuite.store.applyZipLookup()">Fill city/state/county from ZIP</button><button class="btn small ghost" onclick="V14.pushProperty()">Sync to Property</button></div><div class="v20-kpis"><button onclick="mortgageSuite.app.showTrace(\'valueBasis\')"><span>MMW value basis</span><b>'+money(o.value.valueBasis)+'</b></button><button onclick="mortgageSuite.app.showTrace(\'maximumBaseLoan\')"><span>Maximum base mortgage</span><b>'+money(o.loan.maximumBaseLoan)+'</b></button><button onclick="mortgageSuite.app.showTrace(\'totalLoan\')"><span>Total loan</span><b>'+money(o.loan.totalLoan)+'</b></button><button onclick="V20.openAmortization()"><span>Amortization</span><b>Open schedule</b></button></div>'+(Number(i.basePurchasePrice)<500000?'<div class="v20-validation">Purchase price is below the $500,000 scenario-control planning minimum. The entered value is preserved.</div>':'')+(Number(i.asIsValue)!==Number(i.basePurchasePrice)&&!i.v20ValueAuto?'<div class="v20-validation">As-is value differs from the original purchase-price pull. Review the value basis before relying on MMW.</div>':'')+'</div>';body.insertBefore(d,body.firstChild);};

function mapInput(label){var s=String(label).toLowerCase();if(/purchase/.test(s))return['basePurchasePrice','Purchase price','num'];if(/as-is/.test(s))return['asIsValue','As-is value','num'];if(/after-repair|arv/.test(s))return['afterRepairValue','After-repair value','num'];if(/down payment/.test(s))return['finalDownPaymentPct','Down payment %','pct'];if(/renovation|rehab/.test(s))return['reno.baseCost','Renovation base cost','num'];if(/interest/.test(s))return['interestRate','Interest rate %','pct'];if(/term/.test(s))return['termYears','Term years','num'];if(/ufmip rate/.test(s))return['ufmipRate','UFMIP rate %','pct'];return null;}
function installTraceEditor(){var ms=window.mortgageSuite;if(!ms||!ms.app||ms.app.showTrace.__v20)return;var old=ms.app.showTrace.bind(ms.app);ms.app.showTrace=function(key){old(key);setTimeout(function(){var content=document.querySelector('#suite-root .modal-bg:last-child .content');if(!content||content.querySelector('.v20-trace-edit'))return;var trace=ms.store.outputs.traces[key],maps=[],seen={};(trace&&trace.inputs||[]).forEach(function(x){var m=mapInput(x.label);if(m&&!seen[m[0]]){seen[m[0]]=1;maps.push(m);}});var target={finalPurchasePrice:['basePurchasePrice','Purchase price','num'],valueBasis:['asIsValue','As-is value','num'],maximumBaseLoan:['afterRepairValue','After-repair value','num'],totalLoan:['reno.baseCost','Renovation base cost','num']}[key];if(target&&!seen[target[0]])maps.push(target);if(!maps.length)return;var d=document.createElement('div');d.className='v20-trace-edit';d.innerHTML='<h4>Edit inputs here</h4><div class="v20-grid">'+maps.map(function(m){var v=pathGet(ms.store.activeInputs,m[0]);if(m[2]==='pct')v=(Number(v)*100).toFixed(3);return f(m[1],m[0],v,m[2]);}).join('')+'</div><div class="muted small" style="margin-top:7px">Changes recalculate the popup and every linked section immediately.</div>';content.appendChild(d);},0);};ms.app.showTrace.__v20=true;}

V.renderDirectEdit=function(){var store=st(),body=$('screen-body');if(!store||store.snapshot.mode!=='advanced'||!body)return;var old=$('v20Direct');if(old)old.remove();var i=store.activeInputs,d=document.createElement('div');d.id='v20Direct';d.className='v20-direct-edit';d.innerHTML='<b>Direct edit mode</b><div class="muted small">Change core figures here without opening a calculation popup.</div><div class="v20-grid" style="margin-top:9px">'+f('Purchase price','basePurchasePrice',i.basePurchasePrice,'num')+f('As-is value','asIsValue',i.asIsValue,'num')+f('ARV','afterRepairValue',i.afterRepairValue,'num')+f('Down payment %','finalDownPaymentPct',(Number(i.finalDownPaymentPct)*100).toFixed(3),'pct')+'</div>';body.insertBefore(d,body.firstChild);body.classList.add('v20-uw-compact');};

V.renderLive=function(){var store=st(),h=$('v14LiveSummary');if(!store||!h)return;var i=store.activeInputs,o=store.outputs,cap=window.V7&&V7.capacity?V7.capacity():null,maxProperty=cap&&cap.maxLoan?cap.maxLoan/Math.max(.01,1-Number(i.finalDownPaymentPct||0)):0,w=[];if(Number(i.basePurchasePrice)<500000)w.push(['Purchase price below $500,000 planning minimum','setup']);if(!Number(o.loan.totalLoan))w.push(['Loan amount is zero','maxmortgage']);else if(Number(i.basePurchasePrice)&&o.loan.totalLoan<i.basePurchasePrice*.5)w.push(['Loan amount is low relative to purchase price','maxmortgage']);if(Number(i.asIsValue)!==Number(i.basePurchasePrice)&&!i.v20ValueAuto)w.push(['As-is value changed after purchase-price pull','setup']);if(!Number(i.afterRepairValue)&&i.renovation)w.push(['Renovation scenario needs an ARV','setup']);var prior=$('v20LiveExtra');if(prior)prior.remove();var d=document.createElement('div');d.id='v20LiveExtra';d.innerHTML='<div class="v20-live-warnings">'+w.map(function(x){return'<button class="v20-warning" onclick="mortgageSuite.store.navigate({tab:\''+x[1]+'\',section:\''+x[1]+'\'})">'+esc(x[0])+'</button>';}).join('')+'</div><div class="v20-kpis"><button onclick="mortgageSuite.app.showTrace(\'maximumBaseLoan\')"><span>Maximum loan amount</span><b>'+money(o.loan.maximumBaseLoan)+'</b></button><button onclick="V20.openAmortization()"><span>Maximum property value</span><b>'+(maxProperty?money(maxProperty):'Enter qualifying income')+'</b></button><button onclick="mortgageSuite.app.showTrace(\'valueBasis\')"><span>MMW value basis</span><b>'+money(o.value.valueBasis)+'</b></button><button onclick="V20.openAmortization()"><span>Amortization schedule</span><b>View payment detail</b></button></div>';h.appendChild(d);};

V.amortization=function(principal,annualRate,years){var P=Number(principal)||0,r=(Number(annualRate)||0)/12,n=Math.max(1,Math.round((Number(years)||30)*12)),pmt=r?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n,bal=P,rows=[];for(var m=1;m<=n;m++){var interest=bal*r,principalPaid=Math.min(bal,pmt-interest);bal=Math.max(0,bal-principalPaid);rows.push({month:m,payment:pmt,principal:principalPaid,interest:interest,balance:bal});}return{payment:pmt,rows:rows};};
V.openAmortization=function(){var store=st();if(!store)return;var i=store.activeInputs,o=store.outputs,a=V.amortization(o.loan.totalLoan,i.interestRate,i.termYears),annual=[];for(var y=0;y<Math.ceil(a.rows.length/12);y++){var group=a.rows.slice(y*12,y*12+12),pr=group.reduce(function(s,x){return s+x.principal;},0),it=group.reduce(function(s,x){return s+x.interest;},0);annual.push('<tr><td>Year '+(y+1)+'</td><td>'+money(group.reduce(function(s,x){return s+x.payment;},0))+'</td><td>'+money(pr)+'</td><td>'+money(it)+'</td><td>'+money(group[group.length-1].balance)+'</td></tr>');}var bg=document.createElement('div');bg.className='modal-bg no-print';bg.innerHTML='<div class="modal"><header><h3>Amortization schedule</h3><span style="flex:1"></span><button class="btn ghost small">Close</button></header><div class="content"><div class="v20-kpis"><div><span>Loan amount</span><b>'+money(o.loan.totalLoan)+'</b></div><div><span>Rate</span><b>'+(Number(i.interestRate)*100).toFixed(3)+'%</b></div><div><span>Term</span><b>'+i.termYears+' years</b></div><div><span>Monthly P&amp;I</span><b>'+money(a.payment)+'</b></div></div><div class="v20-amort-table"><table><thead><tr><th>Period</th><th>Payments</th><th>Principal</th><th>Interest</th><th>Ending balance</th></tr></thead><tbody>'+annual.join('')+'</tbody></table></div></div></div>';bg.querySelector('button').onclick=function(){bg.remove();};bg.onclick=function(e){if(e.target===bg)bg.remove();};($('suite-root')||document.body).appendChild(bg);};

function rentLookup(){var store=st(),body=$('screen-body');if(!store||store.snapshot.mode!=='rental'||!body||$('v20Rent'))return;var i=store.activeInputs,d=document.createElement('div');d.id='v20Rent';d.className='card v20-rent';d.innerHTML='<h3>Rent lookup by ZIP</h3><div class="body"><div class="v20-grid">'+f('ZIP code','zipCode',i.zipCode,'text')+f('Documented market rent','rental.marketRent',i.rental&&i.rental.marketRent,'num')+'</div><div class="v20-quick"><button class="btn small" onclick="V20.searchRent()">Search rental listings and market rent</button><button class="btn small ghost" onclick="mortgageSuite.store.navigate({tab:\'property\',section:\'property\'})">Open property details</button></div><div class="muted small">Search uses the active ZIP and address. Enter the supported market-rent result manually so no value is invented.</div></div>';var target=body.querySelector('[data-section="rental-income"]')||body.firstChild;if(target&&target.nextSibling)body.insertBefore(d,target.nextSibling);else body.appendChild(d);}
V.searchRent=function(){var store=st(),i=store&&store.activeInputs||{},q=[i.propertyAddress,i.zipCode,'market rent comparable rentals'].filter(Boolean).join(' ');window.open('https://www.google.com/search?q='+encodeURIComponent(q),'_blank','noopener');};

function escrowControl(){var store=st(),body=$('screen-body');if(!store||!['escrow','closing'].includes(store.snapshot.mode)||!body)return;var old=$('v20Escrow');if(old)old.remove();var i=store.activeInputs,o=store.outputs,months=Number(i.reno&&i.reno.paymentReserveMonths)||0,monthly=Number(o.payment.totalMonthlyPayment)||0,d=document.createElement('div');d.id='v20Escrow';d.className='card v20-escrow';d.innerHTML='<h3>Taxes &amp; escrow</h3><div class="body"><div class="v20-grid"><div class="v20-field"><label>Mortgage payments escrowed</label><select class="cell-input" onchange="V20.setScenario(\'mortgagePaymentsEscrowed\',this.value===\'true\',\'bool\')"><option value="true"'+(i.mortgagePaymentsEscrowed!==false?' selected':'')+'>True</option><option value="false"'+(i.mortgagePaymentsEscrowed===false?' selected':'')+'>False</option></select></div>'+f('Payment reserve months','reno.paymentReserveMonths',months,'num')+f('Escrow cushion months','escrow.cushionMonthsOverride',i.escrow&&i.escrow.cushionMonthsOverride,'num')+'</div><div class="v20-kpis"><div><span>Monthly reserve basis</span><b>'+money(monthly)+'</b></div><div><span>Payment reserve</span><b>'+money(i.mortgagePaymentsEscrowed===false?0:monthly*months)+'</b></div><div><span>Monthly tax &amp; insurance</span><b>'+money(o.escrowOut.monthlyDeposit)+'</b></div><div><span>Initial escrow deposit</span><b>'+money(o.escrowOut.initialEscrowDeposit)+'</b></div></div><div class="muted small">Taxes and homeowners insurance use the selected two-month cushion unless manually changed. Payment reserve equals the monthly reserve basis multiplied by the entered months.</div></div>';body.insertBefore(d,body.firstChild);}

function contractorThresholds(){if(!window.V14||!V14.CON)return;var h=$('v14ConBody'),edit=h&&h.querySelector('.v14-doc-inputs');if(!edit||$('v20Threshold'))return;var C=V14.CON;if(C.standardThreshold==null)C.standardThreshold=25000;if(C.highCostThreshold==null)C.highCostThreshold=50000;var threshold=/high/i.test((st()&&st().activeInputs.fhaAreaSelection)||'')?Number(C.highCostThreshold):Number(C.standardThreshold),d=document.createElement('div');d.id='v20Threshold';d.innerHTML='<div class="v20-threshold"><div class="v20-field"><label>Standard item threshold</label><input class="cell-input" inputmode="decimal" value="'+C.standardThreshold+'" onchange="V14.CON.standardThreshold=V20.parseNumber(this.value).value||0;V14.renderContractor()"></div><div class="v20-field"><label>High-cost item threshold</label><input class="cell-input" inputmode="decimal" value="'+C.highCostThreshold+'" onchange="V14.CON.highCostThreshold=V20.parseNumber(this.value).value||0;V14.renderContractor()"></div></div><div class="muted small">Active per-item review threshold: '+money(threshold)+'. Scope, labor, materials, and thresholds remain freeform.</div>';edit.insertBefore(d,edit.firstChild);$$('tbody tr',edit).forEach(function(tr,j){var r=C.rows[j];if(r&&Number(r.material||0)+Number(r.labor||0)>threshold)tr.classList.add('v20-cost-flag');});}

function ocrExtras(){var h=$('v14Prompts');if(!h||$('v20Ocr'))return;var d=document.createElement('div');d.id='v20Ocr';d.className='v20-ocr-extra';d.innerHTML='<button class="btn btn-light btn-sm" onclick="V20.ocr(\'contract\')">Contract</button><button class="btn btn-light btn-sm" onclick="V20.ocr(\'lead\')">Lead expiration</button><button class="btn btn-light btn-sm" onclick="V20.ocr(\'cd\')">Closing Disclosure</button>';h.querySelector('.card-body').appendChild(d);}
V.ocr=function(kind){var text={contract:'Extract buyer, seller, property address, price, earnest money, seller credits, financing terms, closing date, contingencies, contract date, and signature dates. Preserve blanks and mark uncertain fields Needs Review.',lead:'Extract borrower, property, lead source, lead received date, preapproval or rate-lock expiration, follow-up date, owner, status, and notes. Preserve source text and do not infer missing dates.',cd:'Extract loan terms and every Closing Disclosure fee using the page 2 A-J section, payer, paid-before-closing status, credits, cash to close, dates, and totals. Reconcile section and page totals; mark differences Needs Review.'}[kind];var ta=$('aiPrompt')||document.querySelector('#subpanel-docs-import textarea');if(ta){ta.value=(ta.value?ta.value+'\n\n':'')+text;ta.dispatchEvent(new Event('input',{bubbles:true}));}say('OCR prompt added',kind==='cd'?'Closing Disclosure':kind.charAt(0).toUpperCase()+kind.slice(1));};

function plPreview(){var head=$('v13PlModal')&&$('v13PlModal').querySelector('.v13-head');if(!head||$('v20PlPreview'))return;var b=document.createElement('button');b.id='v20PlPreview';b.className='btn btn-light btn-sm';b.textContent='Preview statement';b.onclick=function(){var node=$('v16PlStatement');if(!node)return;var bg=document.createElement('div');bg.className='v13-modal on';bg.innerHTML='<div class="v13-sheet"><div class="v13-head"><b>Profit &amp; Loss Preview</b><span class="v13-grow"></span><button class="btn btn-sm">Close</button></div><div class="v13-body">'+node.outerHTML+'</div></div>';bg.querySelector('button').onclick=function(){bg.remove();};document.body.appendChild(bg);};head.insertBefore(b,head.querySelector('button'));}

function payStatement(){if(window.psStubHTML&&!window.psStubHTML.__v20){var old=window.psStubHTML;window.psStubHTML=function(){var s=old();s=s.replace(/<div class="small" style="margin-top:7px;line-height:1\.5">[\s\S]*?Confirm the current tables before relying on the withholding figures\.\s*<\/div>/,'');return s;};window.psStubHTML.__v20=true;if(window.paintPaystub)paintPaystub();}var b=$('v16PayVoucher');if(b)b.textContent='Classic service-bureau';$$('#subpanel-docs-paystub .note').forEach(function(n){if(/SAMPLE|DEMO|NOT FOR SUBMISSION/i.test(n.textContent||''))n.remove();});}

function stripEditable(){$$('#propBody label .v13-badge.manual').forEach(function(x){if(/^editable$/i.test(x.textContent.trim()))x.remove();});}
function clickableAdvanced(){var store=st();if(!store||store.snapshot.mode!=='advanced')return;$$('#screen-body .warning,#screen-body .warn,#screen-body table tr,#screen-body .kv').forEach(function(el){if(el.__v20||el.closest('input,select,textarea,button'))return;el.__v20=true;el.classList.add('v16-nav-warning');el.onclick=function(){var text=el.textContent||'',tab=/rent/i.test(text)?'rental':/escrow|tax|insurance/i.test(text)?'escrow':/closing|cash|fee/i.test(text)?'closing':/property|value|apprais/i.test(text)?'setup':/renov|contract/i.test(text)?'renovation':'qualify';store.navigate({tab:tab,section:tab});};});}

function sessions(){var tb=document.querySelector('#suite-root .toolbar');if(!tb||!window.LOS||!LOS.AUTO)return;var all=LOS.AUTO.list().slice(0,3),sig=all.map(function(x){return x.ts;}).join('|'),w=$('v20Sessions');if(w&&w.dataset.signature===sig)return;if(w)w.remove();w=document.createElement('span');w.id='v20Sessions';w.dataset.signature=sig;w.className='v20-session';w.innerHTML='<select class="cell-input" aria-label="Last three autosaves"><option value="">Last 3 sessions</option>'+all.map(function(x,i){return'<option value="'+i+'">'+esc(new Date(x.ts).toLocaleString())+' - '+esc(x.name||'Scenario')+'</option>';}).join('')+'</select><button class="btn ghost small">Restore</button>';w.querySelector('button').onclick=function(){var v=w.querySelector('select').value;if(v!=='')LOS.AUTO.restore(Number(v));};tb.appendChild(w);}
function route(){if(V.routed)return;var q=new URLSearchParams(location.search),app=q.get('app'),tab=q.get('tab');if(!app&&!tab)return;V.routed=true;setTimeout(function(){if(app==='income'&&window.SHELL)SHELL.go('calc');else if(window.SHELL)SHELL.go('suite');if(tab&&st())st().navigate({tab:tab,section:tab});else if(st())st().navigate({tab:'setup',section:'setup'});},100);}

function boot(){try{document.documentElement.dataset.losRelease='20';document.documentElement.classList.add('v20-stable');normalizeScenarioRules();ensureOutputAliases();installTraceEditor();V.renderSetup();V.renderDirectEdit();V.renderLive();rentLookup();escrowControl();contractorThresholds();compareColumns();ocrExtras();plPreview();payStatement();stripEditable();clickableAdvanced();sessions();route();if(window.V19)V19.enhanceFreeform(document);}catch(e){if(console&&console.warn)console.warn('v20 enhancement',e);}return true;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setInterval(boot,800);
})();
