/* v21 - correct ARV fit test, direct rent data and final interaction repairs. */
(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var $$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));};
function store(){try{return window.mortgageSuite&&window.mortgageSuite.store;}catch(e){return null;}}
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
function N(v){var n=parseFloat(String(v==null?'':v).replace(/[$,%\s,]/g,''));return isFinite(n)?n:0;}
function money(v){var n=N(v);return(n<0?'-':'')+'$'+Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}
function say(a,b,k){if(window.LOS&&LOS.say)LOS.say(a,b,k||'good',6500);else if(window.toast)toast(a+(b?' - '+b:''));}
var V=window.V21={version:'21.0',rentCache:{}};
try{V.rentCache=JSON.parse(localStorage.getItem('losRentLookup.v21')||'{}');}catch(e){}

/* The old status used valueCushion after the loan was already value-capped,
   which could never be negative. This tests the uncapped MMW cost basis
   directly against 110% of ARV (or HomeStyle's 95% loan/value threshold). */
V.valueFit=function(i,o){i=i||{};o=o||{};var arv=N(i.afterRepairValue),price=N(o.purchase&&o.purchase.finalPurchasePrice||i.basePurchasePrice),asis=N(i.asIsValue)||price,reno=N(o.renovationOut&&o.renovationOut.finalRenovationAmount),isReno=!!(o.renovationActive||i.renovation),isFha=!!o.isFha;
  if(arv<=0)return{status:'na',threshold:isFha&&isReno?110:95,ratio:0,requiredArv:0,shortfall:0,gap:0,message:'Enter an after-repair value to run the value test.'};
  if(isFha&&isReno){var basis=Math.min(price,asis)+reno,ceiling=arv*1.10,ratio=basis/arv*100,required=basis/1.10,gap=basis-ceiling,fail=gap>0.005;return{status:fail?'fail':'pass',threshold:110,ratio:ratio,points:Math.max(0,ratio-110),basis:basis,ceiling:ceiling,requiredArv:required,shortfall:Math.max(0,required-arv),gap:gap,message:fail?'Cost basis exceeds 110% of ARV.':'Cost basis is within 110% of ARV.'};}
  var requested=N(o.loan&&o.loan.baseLoanBeforeLimits||o.loan&&o.loan.maximumBaseLoan),threshold=!isFha&&isReno?95:Math.max(0,(1-N(i.finalDownPaymentPct))*100),ratio2=requested/arv*100,required2=threshold?requested/(threshold/100):0,fail2=ratio2>threshold+.0005;return{status:fail2?'fail':'pass',threshold:threshold,ratio:ratio2,points:Math.max(0,ratio2-threshold),basis:requested,ceiling:arv*threshold/100,requiredArv:required2,shortfall:Math.max(0,required2-arv),gap:requested-arv*threshold/100,message:fail2?'Loan exceeds the program value threshold.':'Loan is within the program value threshold.'};
};
function fitText(f){if(f.status==='na')return f.message;if(f.status==='fail')return'FAIL · '+f.ratio.toFixed(2)+'% of ARV · '+f.points.toFixed(2)+' percentage points above '+f.threshold.toFixed(0)+'% · ARV short '+money(f.shortfall)+' · minimum ARV '+money(f.requiredArv);return'PASS · '+f.ratio.toFixed(2)+'% of ARV · threshold ≤ '+f.threshold.toFixed(0)+'% · '+money(Math.max(0,-f.gap))+' remaining';}
function openArv(){var s=store();if(s)s.navigate({tab:'setup',section:'setup',field:'afterRepairValue'});}
function paintFit(){var s=store();if(!s)return;var f=V.valueFit(s.activeInputs,s.outputs),text=fitText(f);$$('#suite-root .statuspill').forEach(function(el){if(!/after-repair|110%|95%|Fits -|Over by/i.test(el.textContent||''))return;el.className='statuspill v21-fit '+(f.status==='fail'?'bad':f.status==='pass'?'pass':'na');var spans=el.querySelectorAll('span');if(spans[0])spans[0].textContent=f.status==='fail'?'✕':f.status==='pass'?'✓':'i';if(spans[1])spans[1].textContent=text;el.onclick=openArv;el.title='Open ARV inputs';});var live=$('v14LiveSummary');if(!live)return;var old=$('v21ValueFit');if(old)old.remove();var d=document.createElement('button');d.type='button';d.id='v21ValueFit';d.className='v21-value-fit '+(f.status==='fail'?'bad':f.status==='pass'?'pass':'na');d.innerHTML='<span class="mark">'+(f.status==='fail'?'✕':f.status==='pass'?'✓':'i')+'</span><span><b>ARV / program value test — '+f.status.toUpperCase()+'</b><span>'+esc(text)+'. Click to edit ARV.</span></span>';d.onclick=openArv;live.insertBefore(d,live.firstChild);}

/* Renovation remains a permanent workflow. A blank budget no longer turns the
   renovation workflow off; program choice determines 203(k) vs HomeStyle. */
function installRenoBehavior(){if(!window.V20||V20.setScenario.__v21)return;var old=V20.setScenario;V20.setScenario=function(path,raw,kind){var s=store(),i=s&&s.activeInputs,was=!!(i&&i.renovation),blank=path==='reno.baseCost'&&!String(raw==null?'':raw).trim(),ok;if(blank&&s){s.setField('reno.baseCost',0,'Renovation amount cleared');ok=true;}else ok=old(path,raw,kind);i=s&&s.activeInputs;if(!i)return ok;if(path==='renovation'){i.v21RenoIntent=raw===true||String(raw)==='true'||String(raw)==='yes';}if(path==='reno.baseCost'){i.v21RenoIntent=was||N(raw)>0;if(i.v21RenoIntent){i.renovation=true;i.renovationScope='Auto';i.v20RenoWasPositive=false;s.emit();}}return ok;};V20.setScenario.__v21=true;}
function keepReno(){var s=store();if(!s)return;var i=s.activeInputs,changed=false;if(i.v21RenoIntent&&!i.renovation){i.renovation=true;i.renovationScope='Auto';i.v20RenoWasPositive=false;changed=true;}$$('#suite-root button,#suite-root [role="button"]').forEach(function(b){if(/^Renovation$/i.test((b.textContent||'').trim()))b.style.display='';});if(changed)s.emit();var body=$('screen-body');if(s.snapshot.mode!=='renovation'||!body)return;var old=$('v21RenoGate');if(old)old.remove();var label=i.loanProgram==='FHA'?'FHA 203(k)':'Conventional HomeStyle',d=document.createElement('div');d.id='v21RenoGate';d.className='card v21-reno-gate';d.innerHTML='<h3>Renovation program setup</h3><div class="body"><div class="v20-grid"><div class="v20-field"><label>Loan program</label><select class="cell-input" onchange="mortgageSuite.store.switchProgram(this.value)"><option'+(i.loanProgram==='FHA'?' selected':'')+'>FHA</option><option'+(i.loanProgram==='Conventional'?' selected':'')+'>Conventional</option></select></div><div class="v20-field"><label>Renovation amount</label><input class="cell-input" inputmode="decimal" value="'+esc(i.reno&&i.reno.baseCost||'')+'" onchange="V20.setScenario(\'reno.baseCost\',this.value,\'num\')"></div></div><div class="v20-quick"><span class="v21-program-pill">'+label+'</span><span class="muted small">The Renovation tab stays available even when the amount is blank. Entering an amount activates '+label+'.</span></div></div>';body.insertBefore(d,body.firstChild);}

/* 2024 ACS 5-year table B25031 returns median gross rent by bedrooms for a
   ZIP Code Tabulation Area. Values are shown in-suite and never redirect. */
V.parseRentResponse=function(data){if(!Array.isArray(data)||data.length<2)return null;var h=data[0],r=data[1],get=function(k){var x=N(r[h.indexOf(k)]);return x>0&&x<100000?x:null;};return{name:r[h.indexOf('NAME')]||'',total:get('B25031_001E'),studio:get('B25031_002E'),one:get('B25031_003E'),two:get('B25031_004E'),three:get('B25031_005E'),four:get('B25031_006E')};};
V.lookupRent=function(){var el=$('v21RentZip'),z=String(el&&el.value||'').replace(/\D/g,'').slice(0,5);if(z.length!==5)return say('Enter a five-digit ZIP','Market-rent lookup needs a complete ZIP.','warn');var out=$('v21RentResults');if(out)out.innerHTML='<div class="note"><div>Pulling current public rent data…</div></div>';var url='https://api.census.gov/data/2024/acs/acs5?get=NAME,B25031_001E,B25031_002E,B25031_003E,B25031_004E,B25031_005E,B25031_006E&for=zip%20code%20tabulation%20area:'+encodeURIComponent(z);fetch(url).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(function(data){var parsed=V.parseRentResponse(data);if(!parsed)throw new Error('No bedroom rent rows returned');parsed.zip=z;parsed.retrievedAt=new Date().toISOString();V.rentCache[z]=parsed;try{localStorage.setItem('losRentLookup.v21',JSON.stringify(V.rentCache));}catch(e){}renderRentResults(parsed);say('Market rents loaded','Studio through four-bedroom medians are shown inside the suite.');}).catch(function(){if(out)out.innerHTML='<div class="note warn"><div>No public rent row was returned for this ZIP. Keep the entered rent freeform and try another ZIP.</div></div>';});};
V.useRent=function(amount,label){var s=store();if(!s||!N(amount))return;s.setField('rental.mainUnit.gross',N(amount),'ZIP rent lookup — '+label);say('Rent copied',label+' median was placed in Main unit rent.');};
function renderRentResults(x){var out=$('v21RentResults');if(!out||!x)return;var rows=[['Studio',x.studio],['1 bedroom',x.one],['2 bedrooms',x.two],['3 bedrooms',x.three],['4 bedrooms',x.four]];out.innerHTML='<div class="v21-rent-query"><b>'+esc(x.name||('ZIP '+x.zip))+'</b> · 2024 ACS five-year median gross rent by bedrooms</div><table class="v21-rent-table"><thead><tr><th>Unit type</th><th>Median gross rent</th><th>75% planning amount</th><th></th></tr></thead><tbody>'+rows.map(function(r){return'<tr><td>'+r[0]+'</td><td>'+(r[1]?money(r[1]):'Not available')+'</td><td>'+(r[1]?money(r[1]*.75):'—')+'</td><td>'+(r[1]?'<button class="btn small ghost" onclick="V21.useRent('+r[1]+',\''+r[0]+'\')">Use rent</button>':'')+'</td></tr>';}).join('')+'</tbody></table><div class="muted small" style="margin-top:7px">Public-market benchmark for review; the suite keeps the rent manually editable.</div>';}
function rentCard(){var s=store(),body=$('screen-body');if(!s||s.snapshot.mode!=='rental'||!body)return;var d=$('v21Rent');if(!d){d=document.createElement('div');d.id='v21Rent';d.className='card';d.innerHTML='<h3>Market rent by ZIP</h3><div class="body"><div class="v21-rent-head"><div class="v20-field"><label>ZIP code</label><input id="v21RentZip" class="cell-input" inputmode="numeric"></div><button class="btn small" onclick="V21.lookupRent()">Pull market rents</button></div><div class="v21-rent-query">Lookup: “what is market rent for a studio, 1-bedroom, 2-bedroom, 3-bedroom, and 4-bedroom in ZIP code <span id="v21RentQueryZip"></span>?”</div><div id="v21RentResults"></div></div>';body.insertBefore(d,body.firstChild);}var z=String(s.activeInputs.zipCode||''),inp=$('v21RentZip');if(inp&&document.activeElement!==inp)inp.value=z;var q=$('v21RentQueryZip');if(q)q.textContent=z||'_____';if(V.rentCache[z])renderRentResults(V.rentCache[z]);}

function summaryAmortization(){var s=store(),body=$('screen-body');if(!s||s.snapshot.mode!=='summary'||!body||!window.V20)return;var old=$('v21SummaryAmort');if(old)old.remove();var i=s.activeInputs,o=s.outputs,a=V20.amortization(o.loan.totalLoan,i.interestRate,i.termYears),first=a.rows.slice(0,12),totalInterest=a.rows.reduce(function(t,r){return t+r.interest;},0),d=document.createElement('div');d.id='v21SummaryAmort';d.className='card v21-summary-amort';d.innerHTML='<h3>Amortization schedule</h3><div class="body"><div class="v20-kpis"><div><span>Loan amount</span><b>'+money(o.loan.totalLoan)+'</b></div><div><span>Monthly P&amp;I</span><b>'+money(a.payment)+'</b></div><div><span>Total scheduled interest</span><b>'+money(totalInterest)+'</b></div><div><span>Term</span><b>'+N(i.termYears)+' years</b></div></div><div class="table-wrap"><table><thead><tr><th>Month</th><th>Payment</th><th>Principal</th><th>Interest</th><th>Balance</th></tr></thead><tbody>'+first.map(function(r){return'<tr><td>'+r.month+'</td><td>'+money(r.payment)+'</td><td>'+money(r.principal)+'</td><td>'+money(r.interest)+'</td><td>'+money(r.balance)+'</td></tr>';}).join('')+'</tbody></table></div><div class="v20-quick"><button class="btn small" onclick="V20.openAmortization()">Open full annual schedule</button></div></div>';var summary=body.querySelector('[data-section="summary"]'),anchor=summary||$('v15SummaryProperty');if(anchor&&anchor.nextSibling)body.insertBefore(d,anchor.nextSibling);else body.appendChild(d);}

V.setPayStyle=function(style){if(window.V13)V13._payStyle=style;try{if(window.paintPaystub)window.paintPaystub();}catch(e){}var sheet=$('psSheet');if(sheet){sheet.classList.remove('v21-pay-compact','v21-pay-classic','v21-pay-modern','v21-pay-voucher');sheet.classList.add('v21-pay-'+style);}$$('#v21PayStyles button').forEach(function(b){b.classList.toggle('active',b.dataset.style===style);});try{localStorage.setItem('losPayStyle.v21',style);}catch(e){}};
function payPreview(){var stage=$('psStage');if(!stage)return;var bars=$$('#v21PayStyles');bars.slice(1).forEach(function(x){x.remove();});var bar=bars[0];if(!bar){bar=document.createElement('div');bar.id='v21PayStyles';bar.className='no-print';bar.innerHTML='<b>Statement layout</b><button class="btn small" data-style="compact" onclick="V21.setPayStyle(\'compact\')">Compact table</button><button class="btn small" data-style="classic" onclick="V21.setPayStyle(\'classic\')">Classic earnings</button><button class="btn small" data-style="modern" onclick="V21.setPayStyle(\'modern\')">Modern payroll</button><button class="btn small" data-style="voucher" onclick="V21.setPayStyle(\'voucher\')">Service-bureau</button>';stage.parentNode.insertBefore(bar,stage);}var style='modern';try{style=localStorage.getItem('losPayStyle.v21')||'modern';}catch(e){}var sheet=$('psSheet');if(sheet&&!sheet.innerHTML.trim()&&window.paintPaystub)window.paintPaystub();if(sheet&&!sheet.classList.contains('v21-pay-'+style))V.setPayStyle(style);}

function polishSessions(){var w=$('v20Sessions');if(!w)return;w.title='Restore one of the three most recent autosaved sessions';var select=w.querySelector('select');if(select)select.setAttribute('aria-label','Previous session — choose one of the last three');}
function iconSvg(){return'<svg class="v21-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h16M12 4v16"/></svg>';}
function polishIcons(){$$('.btn').forEach(function(b){if(b.dataset.v21Icon||b.querySelector('.v21-icon')||b.id==='themeBtn')return;var t=(b.textContent||'').trim();if(!/^(Pull market rents|Open full annual schedule|Restore|Use rent|Open ARV)/i.test(t))return;b.dataset.v21Icon='1';b.insertAdjacentHTML('afterbegin',iconSvg());});}

function boot(){try{document.documentElement.dataset.losRelease='21';installRenoBehavior();if(window.V20)V20.searchRent=V.lookupRent;keepReno();paintFit();rentCard();summaryAmortization();payPreview();polishSessions();polishIcons();}catch(e){if(console&&console.warn)console.warn('v21 enhancement',e);}return true;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setInterval(boot,700);
})();
