/* v13 — completion workflows. Calculation engines remain untouched. */
(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var $$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));};
function N(v){v=parseFloat(String(v==null?'':v).replace(/[$,%\s]/g,''));return isFinite(v)?v:0;}
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
function usd(v){return '$'+N(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}
function suite(){try{return window.mortgageSuite.store;}catch(e){return null;}}
function say(a,b,k){if(window.LOS&&LOS.say)LOS.say(a,b,k||'good',7000);}
function download(name,obj){var b=new Blob([typeof obj==='string'?obj:JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},500);}
var V13=window.V13={version:'13.0'};

/* Property: one editable field per fact; ZIP-only is a valid partial state. */
function propDefaults(s){s=s||{};[['borrower',''],['street',''],['unit',''],['city',''],['county',''],['state',''],['zip',''],['propType','SFR'],['units',1],['fhaTier','Standard'],['creditScore',740],['projectionYears',5],['apprecPct',3.5]].forEach(function(x){if(s[x[0]]==null)s[x[0]]=x[1];});return s;}
V13.addressLabel=function(s){var a=[s.street,s.unit,s.city,s.state,s.zip].filter(Boolean).join(', ');return a||(s.zip?'ZIP '+s.zip+' — address pending':'Address pending');};
V13.lookupZip=function(){var P=window.LOANSUITE&&LOANSUITE.PROP;if(!P)return;var z=String(P.state.zip||'').replace(/\D/g,'').slice(0,5);if(z.length!==5)return say('Enter a five-digit ZIP','Every address field remains editable.','warn');
  var st=suite(),r=null;try{if(st&&st.lookupZip)r=st.lookupZip(z);else if(window.mortgageSuite&&mortgageSuite.marketData&&mortgageSuite.marketData.lookupZip)r=mortgageSuite.marketData.lookupZip(z);}catch(e){}
  r=r||{};[['city','city'],['state','state'],['county','county'],['propType','propertyType']].forEach(function(m){if(!P.state[m[0]]&&r[m[1]])P.state[m[0]]=r[m[1]];});P.state.lookupSource='ZIP suggestion — review';P.save();P.sync();P.render();say('ZIP suggestion applied','Only blank fields were filled; all fields remain editable.');};
function propField(label,key,val,wide,type){return '<div class="field'+(wide?' wide':'')+'"><label>'+label+' <span class="v13-badge manual">editable</span></label><input class="cell-input" type="'+(type||'text')+'" value="'+esc(val)+'" onchange="LOANSUITE.PROP.set(\''+key+'\',this.value)"></div>';}
function installProperty(){var P=window.LOANSUITE&&LOANSUITE.PROP;if(!P||P.__v13)return false;P.__v13=true;P.state=propDefaults(P.state);var oldSet=P.set.bind(P);P.set=function(k,v){if(k==='zip'){try{oldSet(k,v);}catch(e){}}if(['units','creditScore','projectionYears','apprecPct','currentValue','annualTax','renoCost'].indexOf(k)>=0)v=N(v);P.state[k]=v;if(k==='street'||k==='unit'||k==='city'||k==='state'||k==='zip')P.state.address=V13.addressLabel(P.state);P.save();P.sync();P.render();};
  P.arv=function(){var s=P.state,base=N(s.currentValue)+N(s.renoCost),rate=N(s.apprecPct)/100,yrs=Math.max(1,Math.min(5,Math.round(N(s.projectionYears)||1)));return{base:base,appreciation:base*(Math.pow(1+rate,yrs)-1),arv:base*Math.pow(1+rate,yrs),value:N(s.currentValue),reno:N(s.renoCost),months:yrs*12};};
  P.render=function(){var h=$('propBody');if(!h)return;var s=propDefaults(P.state),a=P.arv(),yrs=Math.max(1,Math.min(5,N(s.projectionYears)||1)),rows='',v=N(s.currentValue)||N(a.base);for(var y=1;y<=5;y++){v=v*(1+N(s.apprecPct)/100);rows+='<tr'+(y===yrs?' class="total"':'')+'><td>Year '+y+'</td><td class="num">'+usd(v)+'</td><td>'+(y===yrs?'Selected horizon':'Scenario estimate')+'</td></tr>';}
    h.innerHTML='<div class="card"><div class="card-top"><span class="tag">Subject</span><span class="doc-name">Freeform property setup</span><div class="spacer"></div><span class="v13-badge '+(s.lookupSource?'review':'manual')+'">'+esc(s.lookupSource||'Manual entry')+'</span></div><div class="card-body"><div class="note"><div>A full address is optional. A five-digit ZIP is enough to begin a partial file and use ZIP-based planning assumptions.</div></div><div class="v13-grid" style="margin-top:12px">'
      +propField('Borrower name','borrower',s.borrower,true)+propField('Street address','street',s.street,true)+propField('Unit','unit',s.unit)+propField('City','city',s.city)+propField('State','state',s.state)+propField('ZIP','zip',s.zip)+propField('County / area','county',s.county)+propField('Property type','propType',s.propType)+propField('Units','units',s.units,false,'number')+propField('FHA area tier','fhaTier',s.fhaTier)+propField('Representative credit score','creditScore',s.creditScore,false,'number')+'</div><div class="v13-actions"><button class="btn btn-primary" onclick="V13.lookupZip()">Optional ZIP auto-lookup</button><span class="muted small">Suggestions fill blanks only and never lock a field.</span></div></div></div>'
      +'<div class="card"><div class="card-top"><span class="tag">Value</span><span class="doc-name">Property and 1–5 year projection</span><div class="spacer"></div><b>'+usd(a.arv)+'</b></div><div class="card-body"><div class="v13-grid">'+propField('Current value','currentValue',s.currentValue,false,'number')+propField('Renovation cost','renoCost',s.renoCost,false,'number')+propField('Annual appreciation / depreciation %','apprecPct',s.apprecPct,false,'number')+propField('Projection years (1–5)','projectionYears',yrs,false,'number')+propField('Annual property tax','annualTax',s.annualTax,false,'number')+'</div><table class="v13-table" style="margin-top:12px"><thead><tr><th>Period</th><th class="num">Projected value</th><th>Basis</th></tr></thead><tbody>'+rows+'</tbody></table><div class="note warn"><div>Scenario estimate only—not an appraisal. Negative assumptions are allowed; every value remains manually editable.</div></div></div></div>';
  };P.render();return true;}

/* Scenario package with schema/version validation and preview before replace. */
V13.scenarioName=function(){var st=suite(),i=st&&st.activeInputs||{},o=st&&st.outputs||{},who=(i.borrowerName||(window.LOANSUITE&&LOANSUITE.PROP.state.borrower)||'Unnamed Borrower').trim(),dp=N(i.finalDownPaymentPct);if(dp<=1)dp*=100;var loan=N(o.loan&&(o.loan.totalLoan||o.loan.maximumBaseLoan)),prog=(i.loanProgram||'Program')+(i.renovation?(i.loanProgram==='FHA'?' 203(k)':' HomeStyle'):'');return who+' – '+dp.toFixed(1)+'% down – '+usd(loan).replace('.00','')+' – '+prog;};
V13.exportScenario=function(){var st=suite();if(!st)return;var pack={schema:'mortgage-suite-scenario',version:1,exportedAt:new Date().toISOString(),name:V13.scenarioName(),inputs:JSON.parse(JSON.stringify(st.activeInputs))};download(pack.name.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')+'.json',pack);};
V13.pickScenario=function(){var f=$('v13ScenarioFile');if(f)f.click();};
V13.readScenario=function(files){var f=files&&files[0];if(!f)return;f.text().then(function(t){var p;try{p=JSON.parse(t);}catch(e){return say('Invalid JSON',e.message,'warn');}if(!p||p.schema!=='mortgage-suite-scenario'||p.version!==1||!p.inputs)return say('Unsupported scenario file','Expected mortgage-suite-scenario version 1.','warn');V13.pendingScenario=p;var st=suite(),cur=st&&st.activeInputs||{},keys=Object.keys(p.inputs),diff=keys.filter(function(k){return JSON.stringify(cur[k])!==JSON.stringify(p.inputs[k]);}).map(function(k){return k+':\n  current: '+JSON.stringify(cur[k])+'\n  import:  '+JSON.stringify(p.inputs[k]);}).join('\n\n')||'No changes.';$('v13Diff').textContent=diff;$('v13ScenarioModal').classList.add('on');});};
V13.applyScenario=function(){var st=suite(),p=V13.pendingScenario;if(!st||!p)return;var target=st.activeInputs;Object.keys(p.inputs).forEach(function(k){if(k!=='id')target[k]=p.inputs[k];});target.name=p.name||V13.scenarioName();if(st.emit)st.emit();$('v13ScenarioModal').classList.remove('on');say('Scenario imported','Reviewed changes were applied to the open scenario.');};

/* PMI worksheet */
V13.pmiCalc=function(){var h=N($('v13PmiHome').value),down=N($('v13PmiDown').value),rate=N($('v13PmiRate').value),term=N($('v13PmiTerm').value)||30,int=N($('v13PmiInterest').value)/100,loan=h*(1-down/100),monthly=loan*rate/100/12,r=int/12,pay=r?loan*r*Math.pow(1+r,term*12)/(Math.pow(1+r,term*12)-1):loan/(term*12),bal=loan,m=0;while(h&&bal/h>.8&&m<term*12){bal=bal*(1+r)-pay;m++;}var total=monthly*m;$('v13PmiResults').innerHTML='<div class="v13-kpis"><div class="v13-kpi"><span>Current LTV</span><b>'+(h?loan/h*100:0).toFixed(2)+'%</b></div><div class="v13-kpi"><span>Annual PMI estimate</span><b>'+rate.toFixed(3)+'%</b></div><div class="v13-kpi"><span>Monthly PMI</span><b>'+usd(monthly)+'</b></div><div class="v13-kpi"><span>Estimated total</span><b>'+usd(total)+'</b></div></div><div class="note"><div>Estimated 80% LTV timing: month '+m+' ('+(m/12).toFixed(1)+' years), assuming scheduled payments and no value change. Automatic termination may follow different rules. Obtain an insurer quote and servicer guidance.</div></div>';};
V13.open=function(id){var m=$(id);if(m)m.classList.add('on');};V13.close=function(id){var m=$(id);if(m)m.classList.remove('on');};V13.print=function(){window.print();};

/* P&L state, analysis and safe date handling. */
var PL=V13.PL={business:'',owner:'',start:'',end:'',prepared:new Date().toISOString().slice(0,10),style:'summary',income:[{name:'Gross receipts',amount:0}],expenses:[{name:'Advertising',amount:0},{name:'Contract labor',amount:0},{name:'Insurance',amount:0},{name:'Office expense',amount:0},{name:'Rent / lease',amount:0},{name:'Repairs',amount:0},{name:'Supplies',amount:0},{name:'Taxes / licenses',amount:0},{name:'Utilities',amount:0},{name:'Other',amount:0}],priorIncome:0,priorExpenses:0,label:'INTERNAL WORKSHEET'};
function plTotals(){var inc=PL.income.reduce(function(a,x){return a+N(x.amount);},0),exp=PL.expenses.reduce(function(a,x){return a+N(x.amount);},0),net=inc-exp,margin=inc?net/inc*100:0,ratio=inc?exp/inc*100:0,change=PL.priorIncome?(inc-N(PL.priorIncome))/N(PL.priorIncome)*100:null,risk=net<0||margin<5?'High':(margin<15||ratio>75?'Moderate':'Low');return{inc:inc,exp:exp,net:net,margin:margin,ratio:ratio,change:change,risk:risk};}
V13.plSet=function(group,i,key,v){if(group==='root')PL[i]=v;else PL[group][i][key]=key==='amount'?N(v):v;V13.renderPL();};V13.plAdd=function(group){PL[group].push({name:'User-defined row',amount:0});V13.renderPL();};V13.plRemove=function(group,i){PL[group].splice(i,1);V13.renderPL();};
V13.plAutofill=function(){var S;try{S=(0,eval)('S');}catch(e){}var b=S&&S.schc&&S.schc[0];if(!b)return say('No self-employment business found','Add a Schedule C business first.','warn');PL.business=b.name||'Business';PL.owner=S.b1||'';var r;try{r=window.calcSchC&&window.calcSchC(b);}catch(e){}if(r&&r.a1)PL.income[0].amount=N(r.a1);say('Self-employment values copied','Only existing entered values were copied; no amount was invented.');V13.renderPL();};
V13.renderPL=function(){var h=$('v13PlBody');if(!h)return;var t=plTotals(),rows=function(g){return PL[g].map(function(x,i){return '<tr><td><input class="cell-input" value="'+esc(x.name)+'" onchange="V13.plSet(\''+g+'\','+i+',\'name\',this.value)"></td><td><input class="cell-input num" value="'+(x.amount||'')+'" onchange="V13.plSet(\''+g+'\','+i+',\'amount\',this.value)"></td><td class="no-print"><button class="btn-icon" onclick="V13.plRemove(\''+g+'\','+i+')">×</button></td></tr>';}).join('');};var insights=[];if(t.change!=null)insights.push('Revenue changed '+t.change.toFixed(1)+'% versus the comparison period.');insights.push(t.net<0?'The covered period reports a net loss.':'The covered period reports positive net income.');if(t.ratio>75)insights.push('Expenses consume more than 75% of revenue.');
  h.innerHTML='<div class="v13-demo"><div class="v13-grid">'+propInput('Business name','business',PL.business)+propInput('Owner / borrower','owner',PL.owner)+propInput('Start date','start',PL.start,'date')+propInput('End date','end',PL.end,'date')+propInput('Date prepared','prepared',PL.prepared,'date')+propInput('Prior-period income','priorIncome',PL.priorIncome,'number')+propInput('Prior-period expenses','priorExpenses',PL.priorExpenses,'number')+'</div><div class="v13-actions"><button class="btn btn-primary" onclick="V13.plAutofill()">Autofill from Self-Employment</button><span class="muted small">Changing dates never changes amounts automatically. Edit manually; no values are silently prorated.</span></div><h3>Income</h3><table class="v13-table"><tbody>'+rows('income')+'</tbody></table><button class="btn btn-light btn-sm no-print" onclick="V13.plAdd(\'income\')">Add income row</button><h3>Expenses</h3><table class="v13-table"><tbody>'+rows('expenses')+'</tbody></table><button class="btn btn-light btn-sm no-print" onclick="V13.plAdd(\'expenses\')">Add expense row</button><div class="v13-kpis"><div class="v13-kpi"><span>Total income</span><b>'+usd(t.inc)+'</b></div><div class="v13-kpi"><span>Total expenses</span><b>'+usd(t.exp)+'</b></div><div class="v13-kpi"><span>Net profit / loss</span><b>'+usd(t.net)+'</b></div><div class="v13-kpi"><span>Net margin</span><b>'+t.margin.toFixed(1)+'%</b></div></div><div class="v13-risk '+t.risk.toLowerCase()+'"><b>'+t.risk+' risk</b><br>'+insights.join(' ')+' Expense ratio: '+t.ratio.toFixed(1)+'%. Review sustainability, recurring obligations, revenue concentration, and supporting bank statements.</div></div>';};
function propInput(label,key,val,type){return '<div class="field"><label>'+label+'</label><input class="cell-input" type="'+(type||'text')+'" value="'+esc(val)+'" onchange="V13.plSet(\'root\',\''+key+'\',null,this.value)"></div>';}

/* Credit: retain original parser/table, add responsibility/linkage/review and transparent rating. */
function installCredit(){if(!window.V12||!V12.CREDIT||V12.__v13)return false;V12.__v13=true;var oldParse=V12.parse;V12.parse=function(text){return oldParse(text).map(function(l){var raw=l.raw||'';l.status=/collection|charge.?off|past due/i.test(raw)?'Derogatory':'Open';l.responsibility=/joint/i.test(raw)?'Joint':(/authorized/i.test(raw)?'Authorized user':'Individual');l.propertyLink=/mortgage|heloc|real estate|property/i.test(raw)?'Subject / REO — review':'';l.review='Needs Review';return l;});};var oldAdd=V12.addLine;V12.addLine=function(){oldAdd();var l=V12.CREDIT.lines[V12.CREDIT.lines.length-1];l.status='Open';l.responsibility='Individual';l.propertyLink='';l.review='Manual Override';V12.render();};var oldSet=V12.set;V12.set=function(id,f,v){var l=V12.CREDIT.lines.filter(function(x){return x.id===id;})[0];if(l&&['status','responsibility','propertyLink','review'].indexOf(f)>=0){l[f]=v;V12.render();return;}oldSet(id,f,v);if(l&&f!=='include'&&f!=='exclude')l.review='Manual Override';};var oldRender=V12.render;V12.render=function(){oldRender();var h=$('v12Body');if(!h||!V12.CREDIT.lines.length)return;var C=V12.CREDIT,high=0,watch=0;C.lines.forEach(function(l){(l.flagList||[]).forEach(function(f){if(f.level==='high')high++;else watch++;});});var rating=high>=3?'High Risk':(high||watch>=3?'Moderate Risk':'Low Risk'),reason=high+' high-priority and '+watch+' review flag(s); '+C.lines.length+' tradelines; '+usd(C.totalBal)+' total balance; '+usd(C.counted)+' counted monthly payments.';var box=document.createElement('div');box.innerHTML='<div class="v13-risk '+rating.split(' ')[0].toLowerCase()+'"><b>Overall credit rating: '+rating+'</b><br>'+reason+' Rating is a transparent worksheet screen, not a credit decision or score.</div><table class="v13-table"><thead><tr><th>Account</th><th>Status</th><th>Responsibility</th><th>Property / mortgage linkage</th><th>Review state</th></tr></thead><tbody>'+C.lines.map(function(l){return '<tr><td>'+esc(l.name)+'</td><td><input class="cell-input" value="'+esc(l.status||'Open')+'" onchange="V12.set(\''+l.id+'\',\'status\',this.value)"></td><td><select class="cell-input" onchange="V12.set(\''+l.id+'\',\'responsibility\',this.value)">'+['Individual','Joint','Authorized user'].map(function(x){return '<option'+(x===l.responsibility?' selected':'')+'>'+x+'</option>';}).join('')+'</select></td><td><input class="cell-input" value="'+esc(l.propertyLink||'')+'" placeholder="Subject, REO #, none" onchange="V12.set(\''+l.id+'\',\'propertyLink\',this.value)"></td><td><select class="cell-input" onchange="V12.set(\''+l.id+'\',\'review\',this.value)">'+['Auto-matched','Needs Review','Manual Override'].map(function(x){return '<option'+(x===(l.review||'Needs Review')?' selected':'')+'>'+x+'</option>';}).join('')+'</select></td></tr>';}).join('')+'</tbody></table>';h.appendChild(box);};return true;}

/* Visible borrower email draft under stipulations. */
function installStips(){if(!window.STIPS||STIPS.__v13)return false;STIPS.__v13=true;var old=STIPS.render;STIPS.render=function(){old();var h=$('stipBody');if(!h)return;var d=document.createElement('div');d.className='card';d.innerHTML='<div class="card-top"><span class="tag">Email</span><span class="doc-name">Generated Email Copy — review before copying</span><div class="spacer"></div><button class="btn btn-primary btn-sm" onclick="STIPS.copy()">Copy draft</button></div><div class="card-body"><textarea class="v13-email" aria-label="Generated borrower email">'+esc(STIPS.text())+'</textarea><div class="muted small">Draft only. Nothing is sent automatically.</div></div>';h.appendChild(d);};STIPS.render();return true;}

function modal(id,title,body){var m=document.createElement('div');m.id=id;m.className='v13-modal';m.innerHTML='<div class="v13-sheet"><div class="v13-head"><b>'+title+'</b><div class="v13-grow"></div><button class="btn btn-light btn-sm no-print" onclick="V13.print()">Print</button><button class="btn btn-sm no-print" onclick="V13.close(\''+id+'\')">Close</button></div><div class="v13-body">'+body+'</div></div>';document.body.appendChild(m);}
function buildModals(){if($('v13PmiModal'))return;
  modal('v13PmiModal','PMI estimate worksheet','<span class="v13-printmark">ESTIMATE — VERIFY WITH INSURER</span><div class="v13-grid" style="margin-top:14px">'+pmiInput('Home price','v13PmiHome',400000)+pmiInput('Down payment %','v13PmiDown',10)+pmiInput('Credit score tier','v13PmiScore','720–759','text')+pmiInput('Interest rate %','v13PmiInterest',6.5)+pmiInput('Term (years)','v13PmiTerm',30)+pmiInput('Estimated annual PMI rate %','v13PmiRate',0.50)+'</div><div class="v13-actions"><button class="btn btn-primary" onclick="V13.pmiCalc()">Calculate estimate</button></div><div id="v13PmiResults"></div><div class="note warn"><div>The 0.50% example for a 720–759 tier is a planning estimate, not guaranteed insurer pricing. Borrower-requested cancellation is commonly associated with 80% LTV, subject to applicable law, seasoning, payment history, value evidence, and servicer rules.</div></div>');
  modal('v13PlModal','Profit & Loss Generator — borrower-provided draft','<div id="v13PlBody"></div>');
  modal('v13RenoModal','Renovation Loan Fee Cheat Sheet','<span class="v13-printmark">INFORMATIONAL ESTIMATES</span><table class="v13-table" style="margin-top:14px"><thead><tr><th>Item</th><th>FHA 203(k)</th><th>HomeStyle</th></tr></thead><tbody><tr><td>Consultant</td><td>Required by scope/program rules; use consultant quote</td><td>Use lender/consultant guidance</td></tr><tr><td>Contingency reserve</td><td>Commonly percentage-based; verify required range</td><td>Commonly percentage-based; verify required range</td></tr><tr><td>Draw inspection</td><td>Per draw × planned draws</td><td>Per draw × planned draws</td></tr><tr><td>Title update</td><td>Per draw × planned draws</td><td>Per draw × planned draws</td></tr><tr><td>Supplemental origination</td><td>Greater of $350 or 1.5% of eligible rehabilitation costs (verify current rule)</td><td>Use lender fee schedule</td></tr><tr><td>Other examples</td><td colspan="2">Architect Fees, Reno Permits, Escrow Holdback, Reno Consultant Fee, Reno Inspection Fee, Reno Title Update</td></tr></tbody></table><div class="note warn"><div>Separate fixed program rules from lender/vendor estimates. Edit the suite Closing section with the actual disclosed or quoted amounts; populated renovation fields flow into the draft LE.</div></div>');
  modal('v13ScenarioModal','Review scenario import','<div class="note warn"><div>Review every difference before replacing values in the open scenario.</div></div><pre class="v13-diff" id="v13Diff"></pre><div class="v13-actions"><button class="btn btn-primary" onclick="V13.applyScenario()">Apply reviewed import</button><button class="btn btn-light" onclick="V13.close(\'v13ScenarioModal\')">Cancel</button></div>');
  var fi=document.createElement('input');fi.type='file';fi.accept='.json,application/json';fi.id='v13ScenarioFile';fi.style.display='none';fi.onchange=function(){V13.readScenario(fi.files);fi.value='';};document.body.appendChild(fi);V13.renderPL();V13.pmiCalc();}
function pmiInput(l,id,v,type){return '<div class="field"><label>'+l+'</label><input class="cell-input" id="'+id+'" type="'+(type||'number')+'" value="'+v+'"></div>';}
function addTools(){var tb=document.querySelector('#suite-root .toolbar');if(!tb||$('v13Tools'))return false;var w=document.createElement('span');w.id='v13Tools';w.className='v13-actions';w.style.margin='0';w.innerHTML='<button class="btn ghost" onclick="V13.exportScenario()">Export Scenario JSON</button><button class="btn ghost" onclick="V13.pickScenario()">Import Scenario JSON</button><button class="btn ghost" onclick="V13.open(\'v13PmiModal\')">PMI Worksheet</button><button class="btn ghost" onclick="V13.open(\'v13PlModal\')">P&amp;L</button><button class="btn ghost" onclick="V13.open(\'v13RenoModal\')">Reno Fees</button>';tb.appendChild(w);return true;}
function addDocsCard(){var h=$('subpanel-docs-paystub');if(!h||$('v13DocsCard'))return false;var d=document.createElement('div');d.id='v13DocsCard';d.className='card';d.innerHTML='<div class="card-top"><span class="tag">Worksheets</span><span class="doc-name">Internal document generators</span></div><div class="card-body"><div class="v13-actions"><button class="btn btn-primary" onclick="V13.open(\'v13PlModal\')">Profit &amp; Loss Generator</button><button class="btn btn-light" onclick="V13.open(\'v13PmiModal\')">PMI Guide / Worksheet</button><button class="btn btn-light" onclick="V13.open(\'v13RenoModal\')">Renovation Fee Cheat Sheet</button></div><div class="note"><div>Generated P&amp;L and payroll worksheets are internal drafts. Paystub outputs in this suite must remain marked SAMPLE / DEMO / NOT FOR SUBMISSION and use generic styling only.</div></div></div>';h.insertBefore(d,h.firstChild);return true;}
V13.paystubStyle=function(s){V13._payStyle=s;if(window.paintPaystub)paintPaystub();};
function installPaystub(){if(!window.psStubHTML||window.psStubHTML.__v13)return false;var old=window.psStubHTML;var wrapped=function(){return '<div class="v13-paystub '+esc(V13._payStyle||'modern')+'">'+old()+'</div>';};wrapped.__v13=true;window.psStubHTML=wrapped;var h=$('subpanel-docs-paystub');if(h&&!$('v13PayStyles')){var d=document.createElement('div');d.id='v13PayStyles';d.className='v13-actions';d.innerHTML='<b>Demo style:</b><button class="btn btn-light btn-sm" onclick="V13.paystubStyle(\'compact\')">Compact corporate table</button><button class="btn btn-light btn-sm" onclick="V13.paystubStyle(\'classic\')">Classic earnings statement</button><button class="btn btn-light btn-sm" onclick="V13.paystubStyle(\'modern\')">Modern payroll statement</button>';var stage=$('psStage');if(stage)stage.parentNode.insertBefore(d,stage);else h.appendChild(d);}if(window.paintPaystub)paintPaystub();return true;}
function reviewBadges(){var host=$('subpanel-docs-import');if(!host)return;$$('input,select',host).forEach(function(el){if(el.__v13review)return;el.__v13review=true;el.addEventListener('change',function(){el.dataset.review='manual';var b=el.parentNode.querySelector('.v13-badge');if(b){b.className='v13-badge manual';b.textContent='Manual Override';}});if(el.parentNode&&el.parentNode.classList&&el.parentNode.classList.contains('field')){var b=document.createElement('span');b.className='v13-badge review';b.textContent='Needs Review';el.parentNode.insertBefore(b,el);}});}
function boot(){buildModals();installProperty();installCredit();installStips();installPaystub();addTools();addDocsCard();reviewBadges();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setInterval(function(){try{boot();}catch(e){}},800);
})();
