/* v25 - modern loan workspace navigation, surface modes and full-file overview. */
(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var $$=function(sel,root){return Array.prototype.slice.call((root||document).querySelectorAll(sel));};
var V=window.V25={version:'25.0',fullActive:false};
var SURFACES=['light','dark','oled'],SURFACE_LABEL={light:'Light surface',dark:'Dark surface',oled:'OLED surface'};
function safeGet(k,d){try{var v=localStorage.getItem(k);return v==null?d:v;}catch(e){return d;}}
function safeSet(k,v){try{localStorage.setItem(k,v);}catch(e){}}
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
function N(v){var n=parseFloat(String(v==null?'':v).replace(/[$,%\s,]/g,''));return isFinite(n)?n:0;}
function money(v){var n=N(v);return(n<0?'-':'')+'$'+Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:0});}
function pct(v){var n=N(v);if(Math.abs(n)<=1)n*=100;return n.toFixed(2).replace(/\.00$/,'')+'%';}
function store(){try{return window.mortgageSuite&&mortgageSuite.store;}catch(e){return null;}}
function navIcon(kind){return '<span class="v23-nav-icon i-'+kind+'" aria-hidden="true"><i></i></span>';}
V.setSurface=function(name){if(SURFACES.indexOf(name)<0)name='dark';document.documentElement.dataset.v25Surface=name;safeSet('los.v25.surface',name);paintSurface();return name;};
V.cycleSurface=function(){var cur=document.documentElement.dataset.v25Surface||safeGet('los.v25.surface','dark'),idx=SURFACES.indexOf(cur);return V.setSurface(SURFACES[(idx<0?1:idx+1)%SURFACES.length]);};
function paintSurface(){var name=document.documentElement.dataset.v25Surface||safeGet('los.v25.surface','dark');if(SURFACES.indexOf(name)<0)name='dark';document.documentElement.dataset.v25Surface=name;var b=$('v25SurfaceButton');if(b){var next=SURFACES[(SURFACES.indexOf(name)+1)%SURFACES.length];b.dataset.value=name;b.title='Surface: '+SURFACE_LABEL[name]+'. Next: '+SURFACE_LABEL[next];b.setAttribute('aria-label',b.title);}}
function installSurface(){var app=$('v23Appearance');if(!app)return;var b=$('v25SurfaceButton');if(!b){b=document.createElement('button');b.id='v25SurfaceButton';b.type='button';b.innerHTML='<span class="v25-surface-art" aria-hidden="true"><i></i></span>';b.onclick=V.cycleSurface;app.insertBefore(b,$('v23InputButton'));}paintSurface();}
function modernHeader(){var top=document.querySelector('#suite-root .topbar'),bar=$('v24ScenarioBar');if(!top||!bar)return;top.classList.add('v25-topbar');bar.classList.add('v25-scenario-control');var pick=bar.querySelector('select'),name=bar.querySelector('input');if(pick){pick.setAttribute('aria-label','Saved scenario');pick.title='Saved scenario';}if(name){name.placeholder='Name this scenario';name.setAttribute('aria-label','Scenario name');name.title='Scenario name — freeform';}if(!$('v25ScenarioMark')){var mark=document.createElement('span');mark.id='v25ScenarioMark';mark.className='v25-scenario-mark';mark.innerHTML='<i></i><span>Scenario</span>';bar.insertBefore(mark,bar.firstChild);}}
function arrangeHeaderRows(){var top=document.querySelector('#suite-root .topbar');if(!top)return;var full=$('v25FullForm');if(!full){full=document.createElement('button');full.id='v25FullForm';full.type='button';full.className='btn ghost no-print';full.innerHTML=navIcon('full')+'<span>Full form</span>';full.onclick=V.openFull;}var main=$('v25HeaderMain'),actions=$('v25HeaderActions');if(!main){main=document.createElement('div');main.id='v25HeaderMain';main.className='v25-header-main';actions=document.createElement('div');actions.id='v25HeaderActions';actions.className='v25-header-actions no-print';top.appendChild(main);top.appendChild(actions);}var actionIds=['v23QuickSave','v23SuiteActions','v24LoanTools','v24LiveSummary','v25FullForm'];if(!full.parentNode)actions.appendChild(full);Array.prototype.slice.call(top.children).forEach(function(node){if(node===main||node===actions)return;if(actionIds.indexOf(node.id)>=0)actions.appendChild(node);else main.appendChild(node);});actionIds.forEach(function(id){var node=$(id);if(node)actions.appendChild(node);});}
function describe(label){var t=String(label||'').toLowerCase();if(/comparison/.test(t))return'Compare saved loan structures';if(/documents|ocr/.test(t))return'Open forms, worksheets and extraction';if(/pmi|mip/.test(t))return'Review mortgage-insurance assumptions';if(/profit|loss/.test(t))return'Prepare the business income worksheet';if(/renovation fee/.test(t))return'Open the renovation fee reference';if(/credit/.test(t))return'Review credit and underwriting details';if(/recalculate/.test(t))return'Refresh every live result';if(/theme|input/.test(t))return'Cycle the current color palette';if(/import/.test(t))return'Load a validated scenario file';if(/export/.test(t))return'Download the active scenario';if(/save/.test(t))return'Preserve the current version';if(/print/.test(t))return'Create a focused print view';if(/session|restore/.test(t))return'Reopen a recent autosave';return'Open this file tool';}
function iconFor(label){var t=String(label||'').toLowerCase();if(/cost|fee|pmi|mip/.test(t))return'coins';if(/credit|review|recalculate/.test(t))return'check';if(/comparison|scenario/.test(t))return'chart';if(/renovation/.test(t))return'home';return'file';}
function decorateMenu(details,title,subtitle){if(!details)return;var panel=details.querySelector('.v23-actions-panel');if(!panel)return;if(!panel.querySelector('.v25-menu-head')){var h=document.createElement('div');h.className='v25-menu-head';h.innerHTML='<div><span>'+esc(title)+'</span><small>'+esc(subtitle)+'</small></div><kbd>Esc</kbd>';panel.insertBefore(h,panel.firstChild);}$$('button',panel).forEach(function(b){if(b.dataset.v25Decorated||b.closest('.v20-session'))return;var label=(b.textContent||'').trim();if(!label)return;b.dataset.v25Decorated='1';b.innerHTML=navIcon(iconFor(label))+'<span class="v25-action-copy"><b>'+esc(label)+'</b><small>'+esc(describe(label))+'</small></span>';});if(!details.dataset.v25Toggle){details.dataset.v25Toggle='1';details.addEventListener('toggle',function(){if(!details.open)return;$$('.v23-action-menu[open],.v23-sync-menu[open]').forEach(function(x){if(x!==details)x.open=false;});});}}
function modernMenus(){decorateMenu($('v23SuiteActions'),'File actions','Save, restore, import, export and print');decorateMenu($('v24LoanTools'),'Loan tools','Analysis, worksheets and underwriting review');decorateMenu($('v23CalcActions'),'Income file actions','Reports, documents and workflow controls');}
function updateSummaryStrip(){var s=store(),strip=$('v25SummaryStrip');if(!s||!strip)return;var i=s.activeInputs||{},o=s.outputs||{},loan=o.loan||{},pay=o.payment||{},cash=o.cash||{},reno=i.reno||{};var values={price:money(i.basePurchasePrice),reno:money(reno.baseCost),loan:money(loan.totalLoan),rate:pct(i.interestRate),payment:money(pay.totalMonthlyPayment),cash:money(cash.cashToClose)};Object.keys(values).forEach(function(k){var b=strip.querySelector('[data-v25-metric="'+k+'"] b');if(b)b.textContent=values[k];});}
function installSummaryStrip(){var stat=$('v24StatStrip'),body=stat&&stat.parentNode;if(!stat||!body)return;var strip=$('v25SummaryStrip');if(!strip){strip=document.createElement('div');strip.id='v25SummaryStrip';strip.className='v25-summary-strip';[['price','Price','Setup'],['reno','Reno','Renovation'],['loan','Loan','Max Mortgage'],['rate','Rate','Mortgage Rates'],['payment','Payment','Qualify'],['cash','Cash to close','Closing']].forEach(function(x){var b=document.createElement('button');b.type='button';b.dataset.v25Metric=x[0];b.dataset.v25Tab=x[2];b.innerHTML='<span>'+x[1]+'</span><b>—</b>';b.onclick=function(){openTab(b.dataset.v25Tab);};strip.appendChild(b);});body.insertBefore(strip,stat);}updateSummaryStrip();}
function valueRows(rows){return'<div class="v25-full-values">'+rows.map(function(r){return'<div><span>'+esc(r[0])+'</span><b>'+esc(r[1])+'</b></div>';}).join('')+'</div>';}
function openButton(label){return'<button type="button" class="v25-open-source" data-v25-tab="'+esc(label)+'">Open '+esc(label.toLowerCase())+'</button>';}
function closingRows(o){var lines=o&&o.closing&&o.closing.lines||[];if(!lines.length)return'<p class="v25-empty">No itemized buyer fee lines are populated yet.</p>';return'<div class="v25-full-lines">'+lines.filter(function(x){return N(x.amount)>0&&!/seller/i.test(x.payer||'');}).map(function(x){return'<div><span>'+esc(x.label||x.name||'Closing cost')+'</span><b>'+money(x.amount)+'</b></div>';}).join('')+'</div>';}
function fullMarkup(s){var i=s.activeInputs||{},o=s.outputs||{},loan=o.loan||{},pay=o.payment||{},cash=o.cash||{},closing=o.closing||{},aus=o.aus||{},warnings=o.warnings||[],reno=i.reno||{};var address=[i.propertyAddress,i.city,i.state,i.zipCode].filter(Boolean).join(', ');return'<section id="v25FullSheet" class="v25-full-sheet"><header><div><span>Complete file view</span><h2>'+esc(i.borrowerName||'Unnamed scenario')+'</h2><p>One continuous read-only view of the live file. Use each section button to edit its source fields.</p></div><div class="v25-full-program">'+esc(i.renovationProgram||i.loanProgram||'Loan')+'</div></header>'+
  '<article class="v25-full-card"><div class="v25-full-title">'+navIcon('file')+'<div><h3>File & property</h3><small>Borrower, address and acquisition basis</small></div>'+openButton('Setup')+'</div>'+valueRows([['Borrower',i.borrowerName||'Not entered'],['Property',address||'TBD / ZIP pending'],['County',i.nyCounty||'Not entered'],['Credit score',i.creditScore||'Not entered'],['Purchase price',money(i.basePurchasePrice)],['As-is value',money(i.asIsValue)],['After-repair value',money(i.afterRepairValue)],['Down payment',pct(i.finalDownPaymentPct)]])+'</article>'+
  '<article class="v25-full-card"><div class="v25-full-title">'+navIcon('home')+'<div><h3>Loan & renovation</h3><small>Program, value basis and financed balance</small></div>'+openButton('Renovation')+'</div>'+valueRows([['Program',i.loanProgram||'Auto'],['Renovation program',i.renovationProgram||'Auto'],['Renovation budget',money(reno.baseCost)],['Note rate',pct(i.interestRate)],['Term',(i.termYears||30)+' years'],['MMW value basis',money(o.value&&o.value.valueBasis)],['Maximum base mortgage',money(loan.maximumBaseLoan)],['Total loan',money(loan.totalLoan)]])+'</article>'+
  '<article class="v25-full-card"><div class="v25-full-title">'+navIcon('coins')+'<div><h3>Costs & escrow</h3><small>Current itemized closing figures</small></div>'+openButton('Closing')+'</div>'+valueRows([['Closing costs',money(closing.buyerClosingCosts)],['Cash to close',money(cash.cashToClose)],['Seller credit',money(cash.sellerConcessionApplied)],['Property taxes',money(i.propertyTaxAmount)],['Homeowners insurance',money(i.homeownersInsuranceAmount)],['Monthly escrow',money(pay.monthlyTaxes+pay.monthlyInsurance)]])+closingRows(o)+'</article>'+
  '<article class="v25-full-card"><div class="v25-full-title">'+navIcon('check')+'<div><h3>Underwriting</h3><small>Income, ratios, reserves and alerts</small></div>'+openButton('Advanced')+'</div>'+valueRows([['Qualifying income',money(aus.totalQualifyingIncome)+' / mo'],['Housing payment',money(aus.housingPayment||pay.totalMonthlyPayment)+' / mo'],['Front-end DTI',pct(aus.frontEndDti)],['Back-end DTI',pct(aus.backEndDti)],['Reserves',money(aus.ownFundReservesAfterClosing)],['Blocking warnings',String(warnings.filter(function(w){return w.level==='error'||w.level==='fail'||w.blocking;}).length)]])+(warnings.length?'<div class="v25-full-alerts">'+warnings.map(function(w){return'<button type="button" data-v25-tab="Advanced"><b>'+esc(w.title||'Review')+'</b><span>'+esc(w.detail||'Open Advanced to review.')+'</span></button>';}).join('')+'</div>':'<p class="v25-pass">No active underwriting warnings.</p>')+'</article>'+
  '<article class="v25-full-card"><div class="v25-full-title">'+navIcon('chart')+'<div><h3>Results</h3><small>Payment and scenario outcome</small></div>'+openButton('Summary')+'</div>'+valueRows([['Principal & interest',money(pay.principalAndInterest)],['Mortgage insurance',money(pay.monthlyFhaMip+pay.monthlyPmi)],['Taxes & insurance',money(pay.monthlyTaxes+pay.monthlyInsurance+pay.hoaMonthly)],['Total payment',money(pay.totalMonthlyPayment)],['Total loan',money(loan.totalLoan)],['Cash to close',money(cash.cashToClose)]])+'</article></section>';}
function openTab(label){var tab=$$('#suite-root .tabs .tab').filter(function(t){return String(t.textContent||'').trim().toUpperCase()===String(label).toUpperCase();})[0];V.fullActive=false;$('suite-root').classList.remove('v25-full-active');if(tab)tab.click();}
function renderFull(){var s=store(),body=$('screen-body');if(!V.fullActive||!s||!body)return;var signature=JSON.stringify([s.activeInputs,s.outputs&&s.outputs.loan,s.outputs&&s.outputs.payment,s.outputs&&s.outputs.cash,s.outputs&&s.outputs.warnings,s.outputs&&s.outputs.closing&&s.outputs.closing.lines]);var old=$('v25FullSheet');if(old&&old.dataset.signature===signature)return;var html=fullMarkup(s);if(old)old.outerHTML=html;else body.insertAdjacentHTML('afterbegin',html);old=$('v25FullSheet');old.dataset.signature=signature;$$('[data-v25-tab]',old).forEach(function(b){b.onclick=function(){openTab(b.dataset.v25Tab);};});}
V.openFull=function(){V.fullActive=true;$('suite-root').classList.add('v25-full-active');renderFull();paintFullNav();window.scrollTo({top:0,behavior:'smooth'});};
function paintFullNav(){var nav=$('v23SuitePrimaryNav');if(!nav)return;$$('button[data-group]',nav).forEach(function(b){var on=V.fullActive&&b.dataset.group==='full';if(V.fullActive||b.dataset.group==='full'){b.classList.toggle('active',on);b.setAttribute('aria-current',on?'page':'false');}});}
function installFullNav(){var nav=$('v23SuitePrimaryNav');if(!nav)return;var b=nav.querySelector('[data-group="full"]');if(!b){b=document.createElement('button');b.type='button';b.dataset.group='full';b.className='v25-full-nav';b.innerHTML=navIcon('full')+'<span>Full</span>';b.setAttribute('aria-label','Full file view');b.onclick=V.openFull;nav.appendChild(b);$$('button:not([data-group="full"])',nav).forEach(function(x){x.addEventListener('click',function(){V.fullActive=false;$('suite-root').classList.remove('v25-full-active');});});$$('#suite-root .tabs .tab').forEach(function(x){if(!x.dataset.v25Exit){x.dataset.v25Exit='1';x.addEventListener('click',function(){V.fullActive=false;$('suite-root').classList.remove('v25-full-active');});}});}if(V.fullActive){$('suite-root').classList.add('v25-full-active');renderFull();paintFullNav();}}
function stabilizeWorksheet(){var card=document.querySelector('#suite-root [data-section="setup"]');if(!card)return;card.classList.add('v24-worksheet-card');var body=card.querySelector(':scope > .body');if(body)body.classList.add('v25-worksheet-stack');}
function keyboardClose(){if(V.keyboardBound)return;V.keyboardBound=true;document.addEventListener('keydown',function(e){if(e.key!=='Escape')return;$$('.v23-action-menu[open],.v23-sync-menu[open]').forEach(function(x){x.open=false;});});}
function boot(){try{document.documentElement.dataset.losRelease='25';if(!document.documentElement.dataset.v25Surface)V.setSurface(safeGet('los.v25.surface','dark'));installSurface();modernHeader();modernMenus();installFullNav();arrangeHeaderRows();installSummaryStrip();stabilizeWorksheet();keyboardClose();if(window.V19)V19.enhanceFreeform(document);}catch(e){if(console&&console.warn)console.warn('v25 enhancement',e);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();if(window.LOS_SCHEDULER)LOS_SCHEDULER.add(boot,1500);else setInterval(boot,1500);
})();
