/* v24 - consolidated worksheet, ten-theme system and reference-backed tools. */
(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var $$=function(sel,root){return Array.prototype.slice.call((root||document).querySelectorAll(sel));};
var V=window.V24={version:'24.0'};
var THEMES=['classic','ledger','slate','bank','graphite','terminal','github','github-dark','lightgray','cloudgrey','nord','dracula','solarized','linear'];/* classic = the release-16 blue/white/green, default since 47 *//* github pair added in release 39 */
var THEME_LABEL={ledger:'Navy ledger',slate:'Slate and teal',bank:'Bank paper',graphite:'Graphite mono',terminal:'Midnight terminal',federal:'Federal blue',clay:'Clay and sand',violet:'Violet fintech',evergreen:'Evergreen ledger',steel:'Steel and amber'};
var INPUTS=['paper','mist','mint','sand','ink'];
var INPUT_LABEL={paper:'Paper',mist:'Mist',mint:'Mint',sand:'Sand',ink:'Ink'};
var QUICK=[
  ['Borrower','borrowerName','text'],['Address','propertyAddress','text'],['ZIP','zipCode','text'],['State','state','text'],['County / area','nyCounty','text'],
  ['Purchase price','basePurchasePrice','number'],['As-is value','asIsValue','number'],['After-repair value','afterRepairValue','number'],['Down %','finalDownPaymentPct','percent'],['Renovation budget','reno.baseCost','number']
];
function st(){try{return window.mortgageSuite&&mortgageSuite.store;}catch(e){return null;}}
function safeGet(k,d){try{var v=localStorage.getItem(k);return v==null?d:v;}catch(e){return d;}}
function safeSet(k,v){try{localStorage.setItem(k,v);}catch(e){}}
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
function N(v){var n=parseFloat(String(v==null?'':v).replace(/[$,%\s,]/g,''));return isFinite(n)?n:0;}
function money(v){var n=N(v);return(n<0?'-':'')+'$'+Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:0});}
function pathGet(obj,path){return String(path).split('.').reduce(function(a,k){return a==null?undefined:a[k];},obj);}
function applyTheme(name,quiet){
  if(THEMES.indexOf(name)<0)name='terminal';
  if(document.documentElement.dataset.v24Theme!==name)document.documentElement.dataset.v24Theme=name;if(safeGet('los.v24.theme','')!==name)safeSet('los.v24.theme',name);
  var base=/^(terminal|github-dark|nord|dracula|linear)$/.test(name)?'dark':'light';
  if(window.LOS&&LOS.setSkin){if(LOS.skin()!==base||document.documentElement.dataset.theme!==base)LOS.setSkin(base);}else if(document.documentElement.dataset.theme!==base)document.documentElement.dataset.theme=base;
  var s=st();if(s&&s.snapshot.theme!==base){s.snapshot.theme=base;if(!quiet)s.emit();}
  paintAppearance();return name;
}
V.setTheme=applyTheme;
V.setInput=function(name){if(INPUTS.indexOf(name)<0)name='ink';document.documentElement.dataset.inputTone=name;safeSet('los.v24.inputTone',name);paintAppearance();return name;};
V.cycleTheme=function(){var cur=document.documentElement.dataset.v24Theme||safeGet('los.v24.theme','terminal'),idx=THEMES.indexOf(cur);applyTheme(THEMES[(idx<0?4:idx+1)%THEMES.length]);};
V.cycleInput=function(){var cur=document.documentElement.dataset.inputTone||safeGet('los.v24.inputTone','ink'),idx=INPUTS.indexOf(cur),next=INPUTS[(idx<0?4:idx+1)%INPUTS.length];V.setInput(next);};
function paintAppearance(){
  var theme=document.documentElement.dataset.v24Theme||safeGet('los.v24.theme','terminal'),tone=document.documentElement.dataset.inputTone||safeGet('los.v24.inputTone','ink');
  if(THEMES.indexOf(theme)<0)theme='terminal';if(INPUTS.indexOf(tone)<0)tone='ink';
  document.documentElement.dataset.v24Theme=theme;document.documentElement.dataset.inputTone=tone;
  var tb=$('v23ThemeButton'),ib=$('v23InputButton');
  if(tb){var nt=THEMES[(THEMES.indexOf(theme)+1)%THEMES.length];tb.onclick=V.cycleTheme;tb.dataset.value=theme;tb.title='Color theme: '+THEME_LABEL[theme]+'. Next: '+THEME_LABEL[nt];tb.setAttribute('aria-label',tb.title);}
  if(ib){var ni=INPUTS[(INPUTS.indexOf(tone)+1)%INPUTS.length];ib.onclick=V.cycleInput;ib.dataset.value=tone;ib.title='Input color: '+INPUT_LABEL[tone]+'. Next: '+INPUT_LABEL[ni];ib.setAttribute('aria-label',ib.title);}
}
function seedAppearance(){
  var first=safeGet('los.v24.seeded','')!=='1',theme=safeGet('los.v24.theme','terminal'),tone=safeGet('los.v24.inputTone','ink');
  if(first){theme='terminal';tone='ink';safeSet('los.v24.seeded','1');safeSet('los.v24.theme',theme);safeSet('los.v24.inputTone',tone);}
  document.documentElement.dataset.inputTone=tone;applyTheme(theme,true);
}
function quickField(label,path,kind){
  var wrap=document.createElement('label');wrap.className='v24-quick-field';wrap.dataset.field=path;
  var cap=document.createElement('span');cap.textContent=label;var input=document.createElement('input');input.className='f text';input.type='text';input.dataset.path=path;input.inputMode=kind==='text'?'text':'decimal';input.autocomplete='off';
  input.addEventListener('change',function(){var s=st();if(!s||input.dataset.v24Committed===input.value)return;var raw=input.value;input.dataset.v24Committed=raw;if(window.V20&&V20.setScenario)V20.setScenario(path,raw,kind==='percent'?'pct':kind==='number'?'num':'text');else s.setField(path,raw,label);});
  wrap.appendChild(cap);wrap.appendChild(input);return wrap;
}
function quickRow(){
  var row=document.createElement('section');row.id='v24WorksheetQuick';row.className='v24-worksheet-row v24-quick-row';
  var rail=document.createElement('div');rail.className='v24-rail-label';rail.innerHTML='<span>Quick edit</span><b id="v24QuickStatus" class="v24-status-chip">Complete</b>';
  var content=document.createElement('div');content.className='v24-rail-content';var grid=document.createElement('div');grid.className='v24-quick-grid';QUICK.forEach(function(x){grid.appendChild(quickField(x[0],x[1],x[2]));});
  var chips=document.createElement('div');chips.className='v24-preset-chips no-print';chips.innerHTML='<button type="button" class="btn small" onclick="V20.setScenario(\'finalDownPaymentPct\',\'3.5\',\'pct\')">FHA 3.5%</button><button type="button" class="btn small ghost" onclick="V20.setScenario(\'finalDownPaymentPct\',\'5\',\'pct\')">5% down</button><button type="button" class="btn small ghost" onclick="mortgageSuite.store.applyZipLookup()">Fill city/state/county from ZIP</button><button type="button" class="btn small ghost" onclick="V14.pushProperty()">Sync to Property</button>';
  content.appendChild(grid);content.appendChild(chips);row.appendChild(rail);row.appendChild(content);return row;
}
function rowShell(key,label){var row=document.createElement('section');row.className='v24-worksheet-row';row.dataset.v24Row=key;var rail=document.createElement('div');rail.className='v24-rail-label';rail.innerHTML='<span>'+esc(label)+'</span><b class="v24-status-chip">Complete</b>';var content=document.createElement('div');content.className='v24-rail-content v24-source-grid';row.appendChild(rail);row.appendChild(content);return row;}
function organiseSetup(card){
  if(!card||card.dataset.v24Worksheet)return;var body=card.querySelector(':scope > .body');if(!body)return;card.dataset.v24Worksheet='1';card.classList.add('v24-worksheet-card');
  var ttl=card.querySelector(':scope > h3 .ttl');if(ttl){ttl.textContent='Worksheet';ttl.title='Everything that defines the file. These selections control what appears on every other tab.';if(!ttl.querySelector('.v24-info'))ttl.insertAdjacentHTML('beforeend',' <span class="v24-info" aria-label="Worksheet information">i</span>');}
  var sum=card.querySelector(':scope > h3 .sum');if(sum)sum.classList.add('v24-heading-summary');
  var quick=quickRow(),groups={transaction:rowShell('transaction','Transaction'),property:rowShell('property','Property'),borrower:rowShell('borrower','Borrower'),terms:rowShell('terms','Rate and terms')};
  var mode='transaction';Array.prototype.slice.call(body.children).forEach(function(node){
    if(node.classList.contains('sec-head')){var t=(node.textContent||'').trim();if(t==='Transaction'){mode='transaction';node.remove();return;}if(t==='Property'){mode='property';node.remove();return;}if(t==='Price & values'){mode='property';node.classList.add('v24-subhead');}if(t==='Financing'){mode='terms';node.remove();return;}if(t==='Taxes, insurance & rounding'){mode='terms';node.classList.add('v24-subhead');}}
    var field=node.dataset&&node.dataset.field;if(field&&QUICK.some(function(x){return x[1]===field;})){node.classList.add('v24-quick-duplicate');}
    if(field==='borrowerName'||field==='creditScore')groups.borrower.lastChild.appendChild(node);else groups[mode].lastChild.appendChild(node);
  });
  body.appendChild(quick);body.appendChild(groups.transaction);body.appendChild(groups.property);body.appendChild(groups.borrower);body.appendChild(groups.terms);
}
function missingMap(i,o){
  var text=(o&&o.warnings||[]).map(function(w){return(w.title||'')+' '+(w.detail||'');}).join(' '),m={};
  if(!N(i.basePurchasePrice))m.basePurchasePrice=true;if(i.renovation&&!N(i.afterRepairValue))m.afterRepairValue=true;
  if(!String(i.zipCode||'').trim()&&/zip/i.test(text))m.zipCode=true;if(!String(i.propertyAddress||'').trim()&&/address/i.test(text))m.propertyAddress=true;if(!String(i.borrowerName||'').trim()&&/borrower.*name/i.test(text))m.borrowerName=true;
  return m;
}
V.missingMap=missingMap;
function updateQuick(){
  var s=st(),row=$('v24WorksheetQuick');if(!s||!row)return;var i=s.activeInputs,o=s.outputs,missing=missingMap(i,o),count=0;
  QUICK.forEach(function(x){var input=row.querySelector('[data-path="'+x[1]+'"]'),wrap=input&&input.closest('.v24-quick-field'),v=pathGet(i,x[1]);if(input&&document.activeElement!==input){if(x[2]==='percent')input.value=v==null?'':String(parseFloat((N(v)*100).toFixed(4)));else input.value=v==null?'':String(v);input.dataset.v24Committed=input.value;}var bad=!!missing[x[1]];if(bad)count++;if(wrap)wrap.classList.toggle('v24-missing',bad);if(input){input.setAttribute('aria-invalid',bad?'true':'false');input.title=bad?'Required by the current scenario warning':'';}});
  var chip=$('v24QuickStatus');if(chip){chip.textContent=count?count+' missing':'Complete';chip.className='v24-status-chip '+(count?'attention':'complete');}
  var property=document.querySelector('[data-v24-row="property"]'),borrower=document.querySelector('[data-v24-row="borrower"]');if(property){var p=N(i.afterRepairValue)||!i.renovation?0:1,pc=property.querySelector('.v24-status-chip');if(pc){pc.textContent=p?'1 missing':'Complete';pc.className='v24-status-chip '+(p?'attention':'complete');}}if(borrower){var bc=borrower.querySelector('.v24-status-chip'),b=!String(i.borrowerName||'').trim();if(bc){bc.textContent=b?'Needs borrower':'Complete';bc.className='v24-status-chip '+(b?'attention':'complete');}}
}
function updateMetrics(strip){var s=st();if(!s||!strip)return;var b=$$('button',strip),o=s.outputs;b.forEach(function(x,idx){var val=x.querySelector('b');if(!val)return;if(idx===0)val.textContent=money(o.value.valueBasis);if(idx===1)val.textContent=money(o.loan.maximumBaseLoan);if(idx===2)val.textContent=money(o.loan.totalLoan);});}
function makeMetricStrip(){var s=st(),o=s.outputs,d=document.createElement('div'),icons=['<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9 20v-5h6v5"/></svg>','<svg viewBox="0 0 24 24"><path d="M4 19V9l8-5 8 5v10"/><path d="M8 13h8M8 16h8M8 19h8"/></svg>','<svg viewBox="0 0 24 24"><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M3 10h18M7 14h4"/></svg>','<svg viewBox="0 0 24 24"><path d="M4 19V5M4 19h16"/><path d="m7 15 4-4 3 2 5-6"/></svg>'];d.id='v24StatStrip';d.className='v20-kpis v24-stat-strip';var rows=[['MMW value basis',money(o.value.valueBasis),"mortgageSuite.app.showTrace('valueBasis')"],['Maximum base mortgage',money(o.loan.maximumBaseLoan),"mortgageSuite.app.showTrace('maximumBaseLoan')"],['Total loan',money(o.loan.totalLoan),"mortgageSuite.app.showTrace('totalLoan')"],['Amortization','Open schedule','V20.openAmortization()']];d.innerHTML=rows.map(function(r,idx){return'<button type="button" onclick="'+r[2]+'"><span class="v22-metric-icon">'+icons[idx]+'</span><span>'+r[0]+'</span><b>'+r[1]+'</b><span class="v22-metric-note" aria-hidden="true"></span></button>';}).join('');return d;}
function integrateSetup(){
  var s=st(),main=$('screen-body');if(!s||s.snapshot.mode!=='setup'||!main)return;var card=main.querySelector('[data-section="setup"]');if(!card)return;organiseSetup(card);
  var legacy=$('v20Setup'),kpis=legacy&&legacy.querySelector('.v20-kpis'),old=$('v24StatStrip');if(kpis){if(old)old.remove();kpis.id='v24StatStrip';kpis.classList.add('v24-stat-strip');card.parentNode.insertBefore(kpis,card);legacy.remove();}else if(!old){old=makeMetricStrip();card.parentNode.insertBefore(old,card);}updateMetrics($('v24StatStrip'));
  var blurb=main.previousElementSibling;if(blurb&&blurb.classList.contains('blurb'))blurb.style.display='none';updateQuick();
}
function stabilizeLegacySetup(){if(!window.V20||!V20.renderSetup||V20.renderSetup.__v24)return;var original=V20.renderSetup;V20.renderSetup=function(force){var s=st();if(!force&&s&&s.snapshot.mode==='setup'&&$('v24WorksheetQuick')){updateQuick();updateMetrics($('v24StatStrip'));return;}return original(force);};V20.renderSetup.__v24=true;}
function contextSummary(){var s=st(),tabs=document.querySelector('#suite-root .tabs');if(!s||!tabs)return;var nav=$('v23SuitePrimaryNav');if(nav&&nav.parentNode!==tabs&&!window.V251)tabs.insertBefore(nav,tabs.firstChild);var el=$('v24ContextSummary');if(!el){el=document.createElement('span');el.id='v24ContextSummary';el.className='v24-context-summary';tabs.appendChild(el);}var i=s.activeInputs,o=s.outputs,state=i.state==='New York'?'NY':i.state||'State',county=i.nyCounty||'County',units=N(i.units)||1;el.textContent=[state,county,units+' '+(units===1?'family':'units'),money(o.purchase.finalPurchasePrice),(N(i.finalDownPaymentPct)*100).toFixed(2)+'% down'].join(' · ');}
function arrangeHeader(){
  var top=document.querySelector('#suite-root .topbar'),toolbar=document.querySelector('#suite-root .toolbar');if(!top||!toolbar)return;if($('v25HeaderMain')){toolbar.classList.add('v24-retired-toolbar');return;}var bar=$('v24ScenarioBar');if(!bar){bar=document.createElement('div');bar.id='v24ScenarioBar';bar.className='v24-scenario-bar';var label=toolbar.querySelector(':scope > .tlabel'),pick=toolbar.querySelector(':scope > select.f.pick'),name=toolbar.querySelector(':scope > input.f.namebox');if(label)label.remove();if(pick)bar.appendChild(pick);if(name)bar.appendChild(name);var spacer=top.querySelector('.spacer');top.insertBefore(bar,spacer||null);}var dates=$$('.datefield',top),after=dates.length?dates[dates.length-1]:null,save=$('v23QuickSave'),actions=$('v23SuiteActions');if(save&&save.parentNode!==top)top.insertBefore(save,after&&after.parentNode===top?after.nextSibling:null);if(actions&&actions.parentNode!==top)top.insertBefore(actions,save&&save.parentNode===top?save.nextSibling:null);toolbar.classList.add('v24-retired-toolbar');
}
V.toggleSummary=function(){var root=$('suite-root'),open=!root.classList.contains('v24-summary-open');root.classList.toggle('v24-summary-open',open);safeSet('los.v24.summaryOpen',open?'1':'0');};
function liveSummaryButton(){var top=document.querySelector('#suite-root .topbar');if(!top||$('v24LiveSummary'))return;var b=document.createElement('button');b.id='v24LiveSummary';b.type='button';b.className='btn ghost v24-live-button';b.textContent='Live summary';b.onclick=V.toggleSummary;top.appendChild(b);if(safeGet('los.v24.summaryOpen','0')==='1')$('suite-root').classList.add('v24-summary-open');}
function animateTabs(){var tabs=document.querySelector('#suite-root .tabs');if(!tabs||tabs.__v24)return;tabs.__v24=true;tabs.addEventListener('click',function(e){if(!e.target.closest('button'))return;var body=$('screen-body');if(!body)return;body.classList.remove('v24-enter');void body.offsetWidth;body.classList.add('v24-enter');setTimeout(function(){body.classList.remove('v24-enter');},240);});}
function findSource(label){var pool=$('v23SuiteActions');return pool&&$$('button',pool).filter(function(b){return(b.textContent||'').trim().toLowerCase()===label.toLowerCase();})[0];}
function splitActions(){
  var file=$('v23SuiteActions'),top=document.querySelector('#suite-root .topbar');if(!file||!top)return;var summary=file.querySelector(':scope > summary span:last-child');if(summary)summary.textContent='File actions';var tools=$('v24LoanTools');if(!tools){tools=document.createElement('details');tools.id='v24LoanTools';tools.className='v23-action-menu no-print';tools.innerHTML='<summary><span class="v23-nav-icon i-dots" aria-hidden="true"><i></i></span><span>Loan tools</span></summary><div class="v23-actions-panel"><div class="v23-actions-grid v24-tools-grid"></div></div>';top.insertBefore(tools,$('v24LiveSummary')||null);var grid=tools.querySelector('.v23-actions-grid');[['Live comparison',function(){if(window.V14)V14.open('v14CompareModal');if(window.V15)V15.renderCompare();}],['Documents & OCR',function(){var t=$$('#suite-root .tab').filter(function(x){return /DOCUMENTS/.test(x.textContent||'');})[0];if(t)t.click();}],['PMI / FHA MIP',function(){if(window.V13)V13.open('v13PmiModal');if(window.V14)V14.loadPmi();}],['Profit & Loss',function(){if(window.V14)V14.open('v13PlModal');}],['Renovation fees',function(){if(window.V13)V13.open('v13RenoModal');}],['Credit review',function(){var t=$$('#suite-root .tab').filter(function(x){return /ADVANCED/.test(x.textContent||'');})[0];if(t)t.click();}],['Recalculate',function(){var s=st();if(s)s.emit();}],['Theme & inputs',function(){V.cycleTheme();}]].forEach(function(x){var b=document.createElement('button');b.type='button';b.className='v23-action';b.textContent=x[0];b.onclick=function(){x[1]();tools.open=false;};grid.appendChild(b);});}
}
V.closeCosts=function(){var d=$('v24CostDrawer');if(d)d.classList.remove('open');};
V.explainCosts=function(){var s=st();if(!s)return;var d=$('v24CostDrawer');if(!d){d=document.createElement('aside');d.id='v24CostDrawer';d.className='v24-cost-drawer';d.innerHTML='<div class="v24-drawer-head"><div><small>Borrower view</small><h2>Closing costs, explained simply</h2></div><button type="button" class="btn ghost" onclick="V24.closeCosts()">Close</button></div><div id="v24CostBody"></div>';document.body.appendChild(d);}var lines=(s.outputs.closing.lines||[]).filter(function(x){return x.payer==='buyer'&&N(x.amount)>0;}),copy={lender:'The lender charges this to prepare and underwrite the loan.',thirdParty:'A separate company provides this required service.',title:'Title work checks ownership and helps protect the transaction.',government:'A government office charges this tax or recording amount.',prepaid:'This is your money set aside for interest, taxes, or insurance rather than a lender fee.',other:'This is another transaction cost already included in the itemized sheet.'};$('v24CostBody').innerHTML='<p>Your current estimate is <b>'+money(s.outputs.closing.buyerClosingCosts)+'</b>. These are the same live itemized amounts used by the Closing tab—nothing new was added.</p><div class="v24-cost-list">'+lines.map(function(x){return'<div><span><b>'+esc(x.label)+'</b><small>'+esc(copy[x.category]||copy.other)+' '+esc(x.basis||'')+'</small></span><strong>'+money(x.amount)+'</strong></div>';}).join('')+'</div>';d.classList.add('open');};
function costExplainLink(){var rows=$$('#suite-root [data-out="Closing costs"],#suite-root [data-out="ESTIMATED CLOSING COSTS"]');rows.forEach(function(row){if(row.querySelector('.v24-explain-costs'))return;var b=document.createElement('button');b.type='button';b.className='v24-explain-costs no-print';b.textContent='Explain';b.onclick=function(e){e.preventDefault();e.stopPropagation();V.explainCosts();};row.appendChild(b);});}
function miRate(profile,i,o){var fico=N(i.creditScore),down=N(i.finalDownPaymentPct),current=N(o.payment.pmiSuggestedRate||o.payment.pmiRateUsed);if(o.isFha){if(profile==='conservative')return Math.max(N(o.payment.fhaMipRateUsed),.0055);return N(o.payment.fhaMipRateUsed)||N(i.fhaAnnualMipRate)||.0055;}if(profile==='standard')return current;if(profile==='aggressive'){if(fico>=760&&down>=.10)return .0009;if(fico>=720)return .0020;if(fico>=680)return .0046;return .0112;}if(fico>=760&&down>=.10)return .0020;if(fico>=720)return .0045;if(fico>=680)return .0085;return .0165;}
V.miRate=miRate;
V.setMiProfile=function(profile){var s=st();if(!s)return;var i=s.activeInputs,o=s.outputs,rate=miRate(profile,i,o);s.setField('v24MiProfile',profile,'Mortgage insurance estimate profile');s.setField(o.isFha?'fhaMipOverrideRate':'pmiOverrideRate',rate,'Mortgage insurance estimate profile');var r=$('v13PmiRate');if(r)r.value=(rate*100).toFixed(3);if(window.V14)V14.pmiLive(true);if(window.V15)V15.renderMI();paintMiProfile();};
function paintMiProfile(){var s=st(),bar=$('v24MiProfiles');if(!s||!bar)return;var p=s.activeInputs.v24MiProfile||'standard';$$('button',bar).forEach(function(b){b.classList.toggle('active',b.dataset.profile===p);});var note=bar.querySelector('small'),r=miRate(p,s.activeInputs,s.outputs);if(note)note.textContent=(s.outputs.isFha?'FHA MIP':'Conventional PMI')+' planning rate '+(r*100).toFixed(3)+'%. Standard preserves the suite default; other profiles use the attached planning ranges.';}
function miProfiles(){var modal=$('v13PmiModal');if(!modal)return;var results=$('v13PmiResults'),bar=$('v24MiProfiles');if(!bar){bar=document.createElement('div');bar.id='v24MiProfiles';bar.className='v24-mi-profiles no-print';bar.innerHTML='<span>Estimate profile</span><div><button type="button" data-profile="aggressive" onclick="V24.setMiProfile(\'aggressive\')">Aggressive</button><button type="button" data-profile="standard" onclick="V24.setMiProfile(\'standard\')">Standard</button><button type="button" data-profile="conservative" onclick="V24.setMiProfile(\'conservative\')">Conservative</button></div><small></small>';if(results)results.parentNode.insertBefore(bar,results);}paintMiProfile();}
function qualificationCards(){var s=st(),main=$('screen-body');if(!s||!main||!/(qualify|rental)/.test(s.snapshot.mode))return;var a=s.outputs.aus,h=N(a.housingPayment),debts=N(a.totalMonthlyLiabilities),sig=[s.snapshot.mode,h,debts,a.fhaSelfSufficiencyRent,a.selfSufficiencyStatus].join('|'),old=$('v24QualificationNeeds');if(old&&old.dataset.sig===sig)return;if(old)old.remove();var fhaFront=h/.31,fhaBack=debts?Math.max(fhaFront,(h+debts)/.43):fhaFront,convFront=h/.36,convBack=debts?Math.max(convFront,(h+debts)/.50):convFront,grossNeeded=h/.75,documented=N(a.fhaSelfSufficiencyRent)/.75,d=document.createElement('div');d.id='v24QualificationNeeds';d.dataset.sig=sig;d.className='card v24-needed-card';d.innerHTML='<h3>Income needed — live planning view</h3><div class="body"><div class="v24-needed-grid"><div><span>FHA front-end</span><b>'+money(fhaFront)+'/mo</b><small>31% housing benchmark</small></div><div><span>FHA back-end</span><b>'+money(fhaBack)+'/mo</b><small>'+(debts?'Includes '+money(debts)+' liabilities':'Same as front-end; no liabilities entered')+'</small></div><div><span>Conventional front-end</span><b>'+money(convFront)+'/mo</b><small>36% manual planning benchmark</small></div><div><span>Conventional back-end</span><b>'+money(convBack)+'/mo</b><small>'+(debts?'50% cap with documented liabilities':'Same as front-end; no liabilities entered')+'</small></div></div><div class="v24-self-suff"><span>Rental income needed for self-sufficiency</span><b>'+money(grossNeeded)+' gross rent / month</b><small>75% of gross must cover '+money(h)+' housing. Documented legal-unit gross: '+money(documented)+'. '+esc(a.selfSufficiencyStatus)+'</small></div></div>';main.insertBefore(d,main.firstChild);}
function boot(){try{var release=parseFloat(document.documentElement.dataset.losRelease||'0');if(!isFinite(release)||release<24)document.documentElement.dataset.losRelease='24';seedAppearance();paintAppearance();arrangeHeader();liveSummaryButton();splitActions();contextSummary();integrateSetup();stabilizeLegacySetup();animateTabs();costExplainLink();miProfiles();qualificationCards();if(window.V19)V19.enhanceFreeform(document);}catch(e){if(console&&console.warn)console.warn('v24 enhancement',e);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();if(window.LOS_SCHEDULER)LOS_SCHEDULER.add(boot,1400);else setInterval(boot,1400);
})();
