/* v14 — professional document workflows and live cross-suite controls. */
(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var $$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));};
function N(v){v=parseFloat(String(v==null?'':v).replace(/[$,%\s]/g,''));return isFinite(v)?v:0;}
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
function money(v){var n=N(v);return (n<0?'-':'')+'$'+Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}
function suite(){try{return window.mortgageSuite.store;}catch(e){return null;}}
function say(a,b,k){if(window.LOS&&LOS.say)LOS.say(a,b,k||'good',7000);}
function modal(id,title,body){if($(id))return;var m=document.createElement('div');m.id=id;m.className='v13-modal v14-modal-print';m.innerHTML='<div class="v13-sheet"><div class="v13-head no-print"><b>'+title+'</b><span class="v13-grow"></span><button class="btn btn-light btn-sm" onclick="V14.printModal(\''+id+'\')">Print</button><button class="btn btn-sm" onclick="V14.close(\''+id+'\')">Close</button></div><div class="v13-body">'+body+'</div></div>';document.body.appendChild(m);}
function field(label,id,value,type,cls){return '<div class="field '+(cls||'')+'"><label>'+label+'</label><input class="cell-input" id="'+id+'" type="'+(type||'text')+'" value="'+esc(value||'')+'"></div>';}
var V=window.V14={};
V.open=function(id){var m=$(id);if(m)m.classList.add('on');};V.close=function(id){var m=$(id);if(m)m.classList.remove('on');};V.printModal=function(){window.print();};

/* Explicit four-theme control shared by both applications. */
V.setTheme=function(name){if(window.LOS&&LOS.setSkin)LOS.setSkin(name);var st=suite();if(st){st.snapshot.theme=name;st.emit();}document.documentElement.setAttribute('data-los-skin',name);document.documentElement.setAttribute('data-theme',name==='light'?'light':'dark');var m=$('v14ThemeMenu');if(m)m.classList.remove('open');};
function addThemeMenu(){var tb=document.querySelector('#suite-root .toolbar');if(!tb||$('v14ThemeMenu'))return false;var w=document.createElement('span');w.id='v14ThemeMenu';w.className='v14-theme-menu';w.innerHTML='<button class="btn ghost" onclick="document.getElementById(\'v14ThemeMenu\').classList.toggle(\'open\')">Theme ▾</button><span class="v14-theme-pop"><button class="btn btn-light btn-sm" onclick="V14.setTheme(\'light\')">Light</button><button class="btn btn-light btn-sm" onclick="V14.setTheme(\'dark\')">Dark</button><button class="btn btn-light btn-sm" onclick="V14.setTheme(\'navy\')">Navy</button><button class="btn btn-light btn-sm" onclick="V14.setTheme(\'oled\')">OLED</button></span>';tb.appendChild(w);return true;}

/* Property pull/push, Google lookup, and address OCR. */
V.pullProperty=function(){var st=suite(),P=window.LOANSUITE&&LOANSUITE.PROP;if(!st||!P)return;var i=st.activeInputs||{};P.state.borrower=i.borrowerName||P.state.borrower||'';P.state.street=i.propertyAddress||P.state.street||'';P.state.zip=i.zipCode||P.state.zip||'';P.state.state=i.state||P.state.state||'';P.state.county=i.nyCounty||P.state.county||'';P.state.units=i.units||P.state.units||1;P.state.propType=i.propertyType||P.state.propType||'';P.state.creditScore=i.creditScore||P.state.creditScore||'';P.state.address=V13.addressLabel(P.state);P.save();P.sync();P.render();say('Property pulled from loan setup','Only fields present in the open scenario were copied.');};
V.pushProperty=function(){var st=suite(),P=window.LOANSUITE&&LOANSUITE.PROP;if(!st||!P)return;var s=P.state;[['borrowerName',s.borrower],['propertyAddress',V13.addressLabel(s)],['zipCode',s.zip],['state',s.state],['units',N(s.units)],['propertyType',s.propType],['creditScore',N(s.creditScore)]].forEach(function(x){if(x[1]!==''&&x[1]!=null)st.setField(x[0],x[1],'Property sync');});if(s.state==='New York'&&s.county)st.setField('nyCounty',s.county,'Property sync');say('Property synced','Property and loan setup now use the same manually editable values.');};
V.googleProperty=function(){var P=window.LOANSUITE&&LOANSUITE.PROP;if(!P)return;var q=V13.addressLabel(P.state);window.open('https://www.google.com/search?q='+encodeURIComponent(q+' property record'),'_blank','noopener');};
V.pickAddressOCR=function(){var f=$('v14AddressFile');if(f)f.click();};
V.addressOCR=function(files){var f=files&&files[0],P=window.LOANSUITE&&LOANSUITE.PROP;if(!f||!P)return;var done=function(text){var t=String(text||'').replace(/\s+/g,' '),m=t.match(/\b(\d{1,6}\s+[A-Za-z0-9 .'-]{2,55}?(?:Street|St|Road|Rd|Avenue|Ave|Boulevard|Blvd|Drive|Dr|Lane|Ln|Court|Ct|Place|Pl|Way))\b.*?\b([A-Za-z .'-]{2,30}),?\s+([A-Z]{2})\s+(\d{5})(?:-\d{4})?/i);if(!m)return say('Address not recognized','Use the freeform fields to enter it manually.','warn');P.state.street=m[1];P.state.city=m[2].trim();P.state.state=m[3].toUpperCase();P.state.zip=m[4];P.state.address=V13.addressLabel(P.state);P.state.lookupSource='OCR — review';P.save();P.sync();P.render();say('Address extracted','Review city, state, ZIP, and county before syncing.');};if(/\.pdf$/i.test(f.name)&&window.pdfText)window.pdfText(f).then(function(r){done(r.text);});else f.text().then(done);};
function enhanceProperty(){var P=window.LOANSUITE&&LOANSUITE.PROP,h=$('propBody');if(!P||!h||$('v14PropertyTools'))return false;var d=document.createElement('div');d.id='v14PropertyTools';d.className='card';d.innerHTML='<div class="card-top"><span class="tag">Sync</span><span class="doc-name">Property and loan setup</span></div><div class="card-body"><div class="v14-bar"><button class="btn btn-primary" onclick="V14.pullProperty()">Pull from loan setup</button><button class="btn btn-primary" onclick="V14.pushProperty()">Auto-sync to other forms</button><button class="btn btn-light" onclick="V14.googleProperty()">Google property search</button><button class="btn btn-light" onclick="V14.pickAddressOCR()">OCR address document</button></div></div>';h.insertBefore(d,h.firstChild);return true;}

/* PMI calculates on every keystroke and writes through to the scenario. */
V.pmiLive=function(sync){if(window.V13&&V13.pmiCalc)V13.pmiCalc();if(!sync)return;var st=suite();if(!st)return;var h=N($('v13PmiHome')&&$('v13PmiHome').value),down=N($('v13PmiDown')&&$('v13PmiDown').value),score=N($('v13PmiScore')&&$('v13PmiScore').value),rate=N($('v13PmiRate')&&$('v13PmiRate').value)/100,int=N($('v13PmiInterest')&&$('v13PmiInterest').value)/100,term=N($('v13PmiTerm')&&$('v13PmiTerm').value);if(h)st.setField('basePurchasePrice',h,'PMI worksheet');if(isFinite(down))st.setField('finalDownPaymentPct',down/100,'PMI worksheet');if(score)st.setField('creditScore',score,'PMI worksheet');if(rate>=0)st.setField('pmiOverrideRate',rate,'PMI worksheet');if(int)st.setField('interestRate',int,'PMI worksheet');if(term)st.setField('termYears',term,'PMI worksheet');};
V.loadPmi=function(){var st=suite();if(!st)return;var i=st.activeInputs,o=st.outputs||{};if($('v13PmiHome'))$('v13PmiHome').value=N(i.basePurchasePrice)||'';if($('v13PmiDown'))$('v13PmiDown').value=(N(i.finalDownPaymentPct)*100)||'';if($('v13PmiScore'))$('v13PmiScore').value=N(i.creditScore)||'';if($('v13PmiInterest'))$('v13PmiInterest').value=(N(i.interestRate)*100)||'';if($('v13PmiTerm'))$('v13PmiTerm').value=N(i.termYears)||30;if($('v13PmiRate'))$('v13PmiRate').value=(N(i.pmiOverrideRate||o.payment&&o.payment.pmiRateUsed)*100)||'';V.pmiLive(false);};
function enhancePmi(){var m=$('v13PmiModal');if(!m||m.__v14)return false;m.__v14=true;$$('input',m).forEach(function(el){el.addEventListener('input',function(){V.pmiLive(true);});});var b=m.querySelector('.v13-actions button');if(b)b.textContent='Synced live';var old=V13.open;V13.open=function(id){old(id);if(id==='v13PmiModal')V14.loadPmi();};return true;}

/* Editable comparison grid; store recalculates each scenario after edit. */
V.compareSet=function(id,path,value){var st=suite(),s=st&&st.snapshot.scenarios[id];if(!s)return;var parts=path.split('.'),t=s.inputs;for(var i=0;i<parts.length-1;i++)t=t[parts[i]];var k=parts[parts.length-1];t[k]=path==='finalDownPaymentPct'||path==='interestRate'?N(value)/100:(path==='basePurchasePrice'?N(value):value);s.updatedAt=new Date().toISOString();st.emit();V.renderCompare();};
V.renderCompare=function(){var st=suite(),h=$('v14CompareBody');if(!st||!h)return;var ids=(st.snapshot.compareIds||[]).slice(0,4);if(ids.length<2)ids=Object.keys(st.snapshot.scenarios).slice(0,4);h.innerHTML='<table class="v13-table v14-comparison"><thead><tr><th>Scenario</th><th>Price</th><th>Down %</th><th>Rate %</th><th>Program</th><th>Loan</th><th>Payment</th><th>Cash to close</th></tr></thead><tbody>'+ids.map(function(id){var s=st.snapshot.scenarios[id],i=s.inputs,o=st.outputsFor(id);return '<tr><td><b>'+esc(i.name)+'</b></td><td><input class="cell-input" value="'+N(i.basePurchasePrice)+'" onchange="V14.compareSet(\''+id+'\',\'basePurchasePrice\',this.value)"></td><td><input class="cell-input" value="'+(N(i.finalDownPaymentPct)*100).toFixed(2)+'" onchange="V14.compareSet(\''+id+'\',\'finalDownPaymentPct\',this.value)"></td><td><input class="cell-input" value="'+(N(i.interestRate)*100).toFixed(3)+'" onchange="V14.compareSet(\''+id+'\',\'interestRate\',this.value)"></td><td><select class="cell-input" onchange="V14.compareSet(\''+id+'\',\'loanProgram\',this.value)"><option'+(i.loanProgram==='FHA'?' selected':'')+'>FHA</option><option'+(i.loanProgram==='Conventional'?' selected':'')+'>Conventional</option></select></td><td>'+money(o.loan.totalLoan)+'</td><td>'+money(o.payment.totalMonthlyPayment)+'</td><td>'+money(o.cash.cashToClose)+'</td></tr>';}).join('')+'</tbody></table>';};
function buildCompare(){if($('v14CompareModal'))return;modal('v14CompareModal','Live scenario comparison','<div id="v14CompareBody"></div>');}

/* Live combined summary and income bridge status. */
V.renderLiveSummary=function(){var st=suite(),h=$('v14LiveSummary');if(!st||!h)return;var o=st.outputs,i=st.activeInputs,t={income:0,pitia:0,debts:0};try{t=window.calcTotals?window.calcTotals():t;}catch(e){}h.innerHTML='<div class="v14-summary"><div><span>Qualifying income</span><b>'+money(t.income)+'/mo</b></div><div><span>Total payment</span><b>'+money(o.payment.totalMonthlyPayment)+'</b></div><div><span>Total loan</span><b>'+money(o.loan.totalLoan)+'</b></div><div><span>Closing costs</span><b>'+money(o.closing.buyerClosingCosts)+'</b></div><div><span>Cash to close</span><b>'+money(o.cash.cashToClose)+'</b></div><div><span>Projected value</span><b>'+money(o.value.projectedValue)+'</b></div></div><div class="muted small">'+esc(i.borrowerName||'Borrower')+' · '+esc(i.propertyAddress||'Property address pending')+' · '+esc(i.loanProgram||'')+'. Income and loan figures update from the current worksheets and scenario.</div>';};
function addLiveSummary(){var root=$('suite-root');if(!root||$('v14LiveSummary'))return false;var h=document.createElement('div');h.id='v14LiveSummary';h.className='card';var main=root.querySelector('.main')||root;main.insertBefore(h,main.firstChild);var st=suite();if(st&&!st.__v14summary){st.__v14summary=true;st.subscribe(V.renderLiveSummary);}V.renderLiveSummary();return true;}

/* Professional P&L output with three accounting layouts and no sample data. */
function plTotals(){var P=V13.PL,inc=P.income.reduce(function(a,x){return a+N(x.amount);},0),exp=P.expenses.reduce(function(a,x){return a+N(x.amount);},0);return{income:inc,expenses:exp,profit:inc-exp,margin:inc?(inc-exp)/inc*100:0};}
V.plStyle=function(s){V13.PL.style=s;V.renderPL();};
V.renderPL=function(){var P=V13.PL,h=$('v13PlBody');if(!P||!h)return;P.style=P.style||'accountant';P.address=P.address||'';P.preparedBy=P.preparedBy||'';P.preparerTitle=P.preparerTitle||'';P.years=P.years||'';P.ownership=P.ownership||'';var t=plTotals();function row(group,x,i){return '<tr><td><input class="cell-input" value="'+esc(x.name)+'" onchange="V13.plSet(\''+group+'\','+i+',\'name\',this.value)"></td><td><input class="cell-input num" value="'+(x.amount||'')+'" onchange="V13.plSet(\''+group+'\','+i+',\'amount\',this.value)"></td><td><button class="btn-icon" onclick="V13.plRemove(\''+group+'\','+i+')">×</button></td></tr>';}
  var input='<div class="v14-doc-inputs"><div class="v14-bar"><b>Layout</b><button class="btn btn-light btn-sm" onclick="V14.plStyle(\'accountant\')">Accountant summary</button><button class="btn btn-light btn-sm" onclick="V14.plStyle(\'ledger\')">Detailed ledger</button><button class="btn btn-light btn-sm" onclick="V14.plStyle(\'condensed\')">Condensed statement</button><button class="btn btn-primary btn-sm" onclick="V13.plAutofill()">Autofill from Self-Employment</button></div><div class="v14-formgrid" style="margin-top:12px">'+plInput('Business','business',P.business)+plInput('Owner / borrower','owner',P.owner)+plInput('Business address','address',P.address,'text','span2')+plInput('Period beginning','start',P.start,'date')+plInput('Period ending','end',P.end,'date')+plInput('Years in operation','years',P.years)+plInput('Ownership %','ownership',P.ownership,'number')+plInput('Prepared by','preparedBy',P.preparedBy)+plInput('Preparer title','preparerTitle',P.preparerTitle)+plInput('Date prepared','prepared',P.prepared,'date')+'</div><h3>Income</h3><table class="v13-table"><tbody>'+P.income.map(function(x,i){return row('income',x,i);}).join('')+'</tbody></table><button class="btn btn-light btn-sm" onclick="V13.plAdd(\'income\')">Add income row</button><h3>Operating expenses</h3><table class="v13-table"><tbody>'+P.expenses.map(function(x,i){return row('expenses',x,i);}).join('')+'</tbody></table><button class="btn btn-light btn-sm" onclick="V13.plAdd(\'expenses\')">Add expense row</button></div>';
  var incRows=P.income.filter(function(x){return x.name||N(x.amount);}).map(function(x){return '<tr><td>'+esc(x.name)+'</td><td class="num">'+money(x.amount)+'</td></tr>';}).join('');var expRows=P.expenses.filter(function(x){return x.name||N(x.amount);}).map(function(x){return '<tr><td>'+esc(x.name)+'</td><td class="num">'+money(x.amount)+'</td></tr>';}).join('');var title=P.style==='condensed'?'Profit & Loss Statement':'Profit & Loss Statement';
  var doc='<div class="v14-doc pl-'+P.style+'"><div class="letterhead">'+(P.preparedBy?'<b>'+esc(P.preparedBy)+'</b><br>'+esc(P.preparerTitle||''):'')+'</div><h1>'+title+'</h1><div class="meta">For the period: <b>'+esc(P.start||'')+(P.start||P.end?' - ':'')+esc(P.end||'')+'</b><br><b>Business:</b> '+esc(P.business||'')+'<br><b>Owner:</b> '+esc(P.owner||'')+(P.address?'<br><b>Address:</b> '+esc(P.address):'')+(P.years?'<br><b>Years in operation:</b> '+esc(P.years):'')+(P.ownership?'<br><b>Ownership:</b> '+esc(P.ownership)+'%':'')+'</div><div class="summary"><div><span>Income</span><b>'+money(t.income)+'</b></div><div><span>Expenses</span><b>'+money(t.expenses)+'</b></div><div><span>Net profit</span><b>'+money(t.profit)+'</b></div></div><h2>Income</h2><table><tbody>'+incRows+'<tr class="total"><td>Total Income</td><td class="num">'+money(t.income)+'</td></tr></tbody></table><h2>Operating Expenses</h2><table><tbody>'+expRows+'<tr class="total"><td>Total Expenses</td><td class="num">'+money(t.expenses)+'</td></tr></tbody></table><table style="margin-top:22px"><tbody><tr class="grand"><td>NET PROFIT'+(t.profit<0?' (LOSS)':'')+'</td><td class="num">'+money(t.profit)+'</td></tr></tbody></table>'+(P.preparedBy?'<div class="prepared"><div class="signature"></div>'+esc(P.preparedBy)+(P.preparerTitle?'<br>'+esc(P.preparerTitle):'')+(P.prepared?'<br>'+esc(P.prepared):'')+'</div>':'')+'</div>';h.innerHTML=input+doc;};
function plInput(label,key,val,type,cls){return '<div class="field '+(cls||'')+'"><label>'+label+'</label><input class="cell-input" type="'+(type||'text')+'" value="'+esc(val||'')+'" onchange="V13.PL[\''+key+'\']=this.value;V14.renderPL()"></div>';}
function enhancePL(){var m=$('v13PlModal');if(!m)return false;var ttl=m.querySelector('.v13-head b');if(ttl)ttl.textContent='Profit & Loss Statement';if(V13.renderPL!==V.renderPL){V13.renderPL=V.renderPL;V.renderPL();}return true;}

/* Keep the required sample marking on payroll output, but make layouts cleaner. */
function enhancePaystub(){if(window.psStubHTML&&!window.psStubHTML.__v14){var old=window.psStubHTML;var wrapped=function(){var s=old();s=s.replace(/<div class="small" style="margin-top:7px;line-height:1.5">[\s\S]*?<\/div>\s*<\/div>$/,'</div>');return s;};wrapped.__v14=true;window.psStubHTML=wrapped;if(window.paintPaystub)paintPaystub();}var h=$('v13PayStyles');if(h&&!h.__v14){h.__v14=true;var b=document.createElement('span');b.className='muted small';b.textContent='Three generic payroll worksheet layouts';h.appendChild(b);}return !!h;}

/* OCR prompt presets add specific output schemas without overwriting user edits. */
V.ocrPrompt=function(kind){var prompts={credit:'Extract creditor, account type, current balance, monthly payment, months remaining, status, responsibility, property linkage, and source text. Mark uncertain values Needs Review.',lease:'Extract landlord, tenants, property address, term dates, monthly rent, security deposit, late fee, utilities, occupants, and signature dates. Return blanks for missing fields.',addendum:'Extract agreement date, purchaser(s), seller(s), property address, amendment text, names, and signature dates. Return blanks for missing fields.',contractor:'Extract contractor/company, license, contact details, customer, property address, proposal/date, permits, and every scope line with labor, materials, and line total. Reconcile subtotals.',income:'Extract borrower, employer/business, pay frequency, rate, hours, current/YTD earnings, taxes, deductions, net pay, period dates, and document source. Do not infer missing amounts.'};var ta=$('aiPrompt')||document.querySelector('#subpanel-docs-import textarea');if(ta){ta.value=(ta.value?ta.value+'\n\n':'')+prompts[kind];ta.dispatchEvent(new Event('input',{bubbles:true}));}else navigator.clipboard&&navigator.clipboard.writeText(prompts[kind]);say('OCR prompt added',kind.charAt(0).toUpperCase()+kind.slice(1)+' extraction fields were added.');};
function addPromptOptions(){var h=$('subpanel-docs-import');if(!h||$('v14Prompts'))return false;var d=document.createElement('div');d.id='v14Prompts';d.className='card';d.innerHTML='<div class="card-top"><span class="tag">OCR</span><span class="doc-name">Extraction prompt presets</span></div><div class="card-body"><div class="v14-bar"><button class="btn btn-light btn-sm" onclick="V14.ocrPrompt(\'income\')">Income</button><button class="btn btn-light btn-sm" onclick="V14.ocrPrompt(\'credit\')">Credit report</button><button class="btn btn-light btn-sm" onclick="V14.ocrPrompt(\'lease\')">Lease</button><button class="btn btn-light btn-sm" onclick="V14.ocrPrompt(\'addendum\')">Addendum</button><button class="btn btn-light btn-sm" onclick="V14.ocrPrompt(\'contractor\')">Contractor estimate</button></div></div>';h.insertBefore(d,h.firstChild);return true;}

/* Lease and purchase-contract addendum generators. */
V.LEASE={landlord:'',tenant:'',property:'',start:'',end:'',rent:'',dueDay:'1',deposit:'',lateFee:'',utilities:'',occupants:'',terms:''};
V.ADD={agreementDate:'',purchaser:'',seller:'',property:'',terms:'',buyer1:'',buyer2:'',seller1:'',seller2:''};
V.docSet=function(type,key,value){V[type][key]=value;type==='LEASE'?V.renderLease():V.renderAddendum();};
function docInput(type,label,key,val,cls,typeAttr){return '<div class="field '+(cls||'')+'"><label>'+label+'</label><input class="cell-input" type="'+(typeAttr||'text')+'" value="'+esc(val||'')+'" onchange="V14.docSet(\''+type+'\',\''+key+'\',this.value)"></div>';}
V.renderLease=function(){var x=V.LEASE,h=$('v14LeaseBody');if(!h)return;var f='<div class="v14-doc-inputs"><div class="v14-formgrid">'+docInput('LEASE','Landlord','landlord',x.landlord,'span2')+docInput('LEASE','Tenant(s)','tenant',x.tenant,'span2')+docInput('LEASE','Property address','property',x.property,'span4')+docInput('LEASE','Lease start','start',x.start,'','date')+docInput('LEASE','Lease end','end',x.end,'','date')+docInput('LEASE','Monthly rent','rent',x.rent,'','number')+docInput('LEASE','Rent due day','dueDay',x.dueDay,'','number')+docInput('LEASE','Security deposit','deposit',x.deposit,'','number')+docInput('LEASE','Late fee','lateFee',x.lateFee,'','number')+docInput('LEASE','Utilities / responsibilities','utilities',x.utilities,'span2')+docInput('LEASE','Authorized occupants','occupants',x.occupants,'span2')+docInput('LEASE','Additional terms','terms',x.terms,'span2')+'</div><div class="v14-bar" style="margin-top:10px"><button class="btn btn-light" onclick="V14.pickDocOCR(\'LEASE\')">OCR lease</button></div></div>';
  var d='<div class="v14-doc"><h1>Residential Lease Agreement</h1><p>This Residential Lease Agreement is made between <b>'+esc(x.landlord)+'</b> (Landlord) and <b>'+esc(x.tenant)+'</b> (Tenant).</p><h2>Premises and term</h2><p>The premises are located at <b>'+esc(x.property)+'</b>. The lease begins '+esc(x.start)+' and ends '+esc(x.end)+'.</p><h2>Rent and security deposit</h2><p>Monthly rent is <b>'+money(x.rent)+'</b>, due on day '+esc(x.dueDay)+' of each month. The security deposit is <b>'+money(x.deposit)+'</b>. The stated late fee is <b>'+money(x.lateFee)+'</b>.</p><h2>Occupancy and utilities</h2><p>Authorized occupants: '+esc(x.occupants)+'.</p><p>Utilities and responsibilities: '+esc(x.utilities)+'.</p>'+(x.terms?'<h2>Additional terms</h2><p>'+esc(x.terms).replace(/\n/g,'<br>')+'</p>':'')+'<div style="display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:70px"><div class="signature">Landlord / Date</div><div class="signature">Tenant / Date</div></div></div>';h.innerHTML=f+d;};
V.renderAddendum=function(){var x=V.ADD,h=$('v14AddBody');if(!h)return;var f='<div class="v14-doc-inputs"><div class="v14-formgrid">'+docInput('ADD','Agreement date','agreementDate',x.agreementDate,'','date')+docInput('ADD','Purchaser(s)','purchaser',x.purchaser,'span2')+docInput('ADD','Seller(s)','seller',x.seller,'span2')+docInput('ADD','Property','property',x.property,'span4')+'<div class="field span4"><label>Amendment terms</label><textarea class="v13-email" onchange="V14.docSet(\'ADD\',\'terms\',this.value)">'+esc(x.terms)+'</textarea></div>'+docInput('ADD','Buyer 1','buyer1',x.buyer1)+docInput('ADD','Buyer 2','buyer2',x.buyer2)+docInput('ADD','Seller 1','seller1',x.seller1)+docInput('ADD','Seller 2','seller2',x.seller2)+'</div><div class="v14-bar" style="margin-top:10px"><button class="btn btn-light" onclick="V14.pickDocOCR(\'ADD\')">OCR addendum</button></div></div>';
  var d='<div class="v14-doc" style="font-family:Georgia,serif"><h1 style="text-decoration:underline;font-size:19px">ADDENDUM TO REAL ESTATE PURCHASE AND SALE<br>AGREEMENT</h1><p style="margin-top:54px">The undersigned parties to a Purchase and Sale Agreement dated <u>'+esc(x.agreementDate)+'　　　　　　</u>, by and between <u>'+esc(x.purchaser)+'　　　　　　　　　</u> ("Purchaser"), and <u>'+esc(x.seller)+'　　　　　　　　　</u> ("Seller"), for the purchase and sale of that certain property municipally known as <u>'+esc(x.property)+'　　　　　　　　　</u> ("Property"), hereby mutually agree to amend said Agreement as follows:</p><div style="min-height:250px;border-bottom:1px solid #777;padding-top:24px">'+esc(x.terms).replace(/\n/g,'<br>')+'</div><p style="text-align:center;margin-top:28px">All other terms and conditions of the Sales Contract remain the same.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:22px 80px;margin-top:55px"><b>BUYER(S):</b><span></span><div class="signature">'+esc(x.buyer1)+' / Date</div><div class="signature">'+esc(x.buyer2)+' / Date</div><b>SELLER(S):</b><span></span><div class="signature">'+esc(x.seller1)+' / Date</div><div class="signature">'+esc(x.seller2)+' / Date</div></div></div>';h.innerHTML=f+d;};
V.pickDocOCR=function(type){V._ocrType=type;var f=$('v14DocFile');if(f)f.click();};
V.docOCR=function(files){var f=files&&files[0];if(!f)return;var done=function(text){var t=String(text||'').replace(/\s+/g,' ');if(V._ocrType==='ADD'){var x=V.ADD,m=t.match(/dated\s+(.{3,35}?),?\s+by and between\s+(.{3,70}?)\s*\(.*?Purchaser.*?\),?\s+and\s+(.{3,70}?)\s*\(.*?Seller/i);if(m){x.agreementDate=m[1].trim();x.purchaser=m[2].trim();x.seller=m[3].trim();}var p=t.match(/municipally known as\s+(.{5,120}?)\s*\(.*?Property/i);if(p)x.property=p[1].trim();V.renderAddendum();}else{var l=V.LEASE,addr=t.match(/(?:premises|property)(?: located)?(?: at|:)\s*(.{5,100}?)(?:\.|,\s*(?:term|lease))/i);if(addr)l.property=addr[1].trim();var rent=t.match(/(?:monthly rent|rent)\s*(?:is|:)?\s*\$?([\d,]+(?:\.\d{2})?)/i);if(rent)l.rent=N(rent[1]);var dep=t.match(/security deposit\s*(?:is|:)?\s*\$?([\d,]+(?:\.\d{2})?)/i);if(dep)l.deposit=N(dep[1]);V.renderLease();}say('Document fields extracted','Review all values before printing.');};if(/\.pdf$/i.test(f.name)&&window.pdfText)window.pdfText(f).then(function(r){done(r.text);});else f.text().then(done);};
function buildLegalDocs(){if(!$('v14LeaseModal')){modal('v14LeaseModal','Residential Lease Agreement','<div id="v14LeaseBody"></div>');modal('v14AddModal','Purchase and Sale Agreement Addendum','<div id="v14AddBody"></div>');var f=document.createElement('input');f.type='file';f.accept='.pdf,.txt';f.style.display='none';f.id='v14DocFile';f.onchange=function(){V.docOCR(f.files);f.value='';};document.body.appendChild(f);V.renderLease();V.renderAddendum();}}

/* Contractor estimate: searchable scope rows, OCR, reconciliation, and renovation sync. */
V.CON={company:'',companyAddress:'',license:'',phone:'',email:'',customer:'',property:'',date:'',proposal:'',permits:'',overheadPct:0,contingencyPct:0,rows:[]};
V.CON_CATS=['Architect / plans','Bathroom renovation','Cabinets / countertops','Cleanup and debris removal','Doors and hardware','Drywall and paint preparation','Electrical panel / rewiring','Exterior siding','Flooring','Framing','Gutters and downspouts','HVAC','Insulation','Kitchen renovation','Painting','Permits','Plumbing','Roofing','Structural repair / masonry','Windows'];
V.conAdd=function(name){V.CON.rows.push({description:name||'',material:0,labor:0});V.renderContractor();};V.conSet=function(i,k,v){if(i==='root')V.CON[k]=v;else V.CON.rows[i][k]=(k==='description'?v:N(v));V.renderContractor();};V.conRemove=function(i){V.CON.rows.splice(i,1);V.renderContractor();};
function conTotals(){var mat=0,lab=0;V.CON.rows.forEach(function(r){mat+=N(r.material);lab+=N(r.labor);});var base=mat+lab,over=base*N(V.CON.overheadPct)/100,cont=(base+over)*N(V.CON.contingencyPct)/100;return{material:mat,labor:lab,base:base,overhead:over,contingency:cont,total:base+over+cont};}
V.conSearch=function(q){var h=$('v14ConSearchResults');if(!h)return;q=String(q||'').toLowerCase();h.innerHTML=V.CON_CATS.filter(function(x){return !q||x.toLowerCase().indexOf(q)>=0;}).map(function(x){return '<button onclick="V14.conAdd(\''+esc(x).replace(/'/g,"\\'")+'\')">'+esc(x)+'</button>';}).join('');};
V.lookupCost=function(desc){var st=suite(),i=st&&st.activeInputs||{},place=[i.zipCode,i.state].filter(Boolean).join(' ');window.open('https://www.google.com/search?q='+encodeURIComponent((desc||'home renovation')+' labor material cost '+place),'_blank','noopener');};
V.conSync=function(){var st=suite(),t=conTotals();if(!st)return;st.setField('reno.baseCost',t.total,'Contractor estimate');say('Contractor total synced','The estimate grand total now drives the renovation base cost.');};
V.renderContractor=function(){var x=V.CON,h=$('v14ConBody');if(!h)return;var t=conTotals(),checks=[];if(!x.company)checks.push(['bad','Contractor/company is blank.']);if(!x.property)checks.push(['bad','Property address is blank.']);if(!x.rows.length)checks.push(['bad','No scope lines entered.']);if(x.rows.some(function(r){return !r.description;}))checks.push(['bad','A scope line is missing its description.']);if(Math.abs(t.total-(t.base+t.overhead+t.contingency))<.01)checks.push(['good','Labor, materials, overhead, contingency, and grand total reconcile.']);var edit='<div class="v14-doc-inputs"><div class="v14-formgrid">'+conInput('Company','company',x.company,'span2')+conInput('License','license',x.license)+conInput('Date','date',x.date,'','date')+conInput('Company address','companyAddress',x.companyAddress,'span2')+conInput('Phone','phone',x.phone)+conInput('Email','email',x.email)+conInput('Customer / Bill to','customer',x.customer,'span2')+conInput('Property address','property',x.property,'span2')+conInput('Proposal / reference','proposal',x.proposal)+conInput('Permits required','permits',x.permits)+conInput('Overhead & profit %','overheadPct',x.overheadPct,'','number')+conInput('Contingency %','contingencyPct',x.contingencyPct,'','number')+'</div><div class="v14-section"><div class="v14-bar"><input class="cell-input" id="v14ConSearch" placeholder="Search work categories" oninput="V14.conSearch(this.value)"><button class="btn btn-light" onclick="V14.conAdd(\'\')">Add custom row</button><button class="btn btn-light" onclick="V14.pickConOCR()">OCR estimate</button><button class="btn btn-primary" onclick="V14.conSync()">Use total in renovation</button></div><div class="v14-search-results" id="v14ConSearchResults"></div></div><table class="v13-table"><thead><tr><th>Description</th><th>Material</th><th>Labor</th><th>Total</th><th></th></tr></thead><tbody>'+x.rows.map(function(r,i){return '<tr><td><input class="cell-input" value="'+esc(r.description)+'" onchange="V14.conSet('+i+',\'description\',this.value)"></td><td><input class="cell-input num" value="'+(r.material||'')+'" onchange="V14.conSet('+i+',\'material\',this.value)"></td><td><input class="cell-input num" value="'+(r.labor||'')+'" onchange="V14.conSet('+i+',\'labor\',this.value)"></td><td>'+money(N(r.material)+N(r.labor))+'</td><td><button class="btn-icon" onclick="V14.conRemove('+i+')">×</button></td></tr>';}).join('')+'</tbody></table>'+checks.map(function(c){return '<div class="v14-check '+c[0]+'">'+c[1]+'</div>';}).join('')+'</div>';
  var rows=x.rows.map(function(r){return '<tr><td>'+esc(r.description)+'</td><td class="num">'+money(r.material)+'</td><td class="num">'+money(r.labor)+'</td><td class="num">'+money(N(r.material)+N(r.labor))+'</td></tr>';}).join('');var doc='<div class="v14-doc"><h1>Contractor Estimate</h1><div class="meta"><b>'+esc(x.company)+'</b><br>'+esc(x.companyAddress)+(x.license?'<br>License: '+esc(x.license):'')+(x.phone?'<br>'+esc(x.phone):'')+(x.email?' · '+esc(x.email):'')+'</div><table><tbody><tr><td><b>Customer</b><br>'+esc(x.customer)+'</td><td><b>Property</b><br>'+esc(x.property)+'</td><td><b>Date</b><br>'+esc(x.date)+'<br><b>Reference</b><br>'+esc(x.proposal)+'</td></tr></tbody></table><h2>Description of Work</h2><table><thead><tr><th>Description</th><th class="num">Material</th><th class="num">Labor</th><th class="num">Total</th></tr></thead><tbody>'+rows+'<tr class="total"><td>Subtotals</td><td class="num">'+money(t.material)+'</td><td class="num">'+money(t.labor)+'</td><td class="num">'+money(t.base)+'</td></tr>'+(t.overhead?'<tr><td>Overhead & profit ('+N(x.overheadPct).toFixed(1)+'%)</td><td></td><td></td><td class="num">'+money(t.overhead)+'</td></tr>':'')+(t.contingency?'<tr><td>Contingency ('+N(x.contingencyPct).toFixed(1)+'%)</td><td></td><td></td><td class="num">'+money(t.contingency)+'</td></tr>':'')+'<tr class="grand"><td colspan="3">GRAND TOTAL</td><td class="num">'+money(t.total)+'</td></tr></tbody></table><p><b>Permits required:</b> '+esc(x.permits)+'</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:55px;margin-top:70px"><div class="signature">Contractor signature / Date</div><div class="signature">Owner / Borrower signature / Date</div></div></div>';h.innerHTML=edit+doc;V.conSearch($('v14ConSearch')&&$('v14ConSearch').value);};
function conInput(label,key,val,cls,type){return '<div class="field '+(cls||'')+'"><label>'+label+'</label><input class="cell-input" type="'+(type||'text')+'" value="'+esc(val||'')+'" onchange="V14.conSet(\'root\',\''+key+'\',this.value)"></div>';}
V.pickConOCR=function(){var f=$('v14ConFile');if(f)f.click();};V.conOCR=function(files){var f=files&&files[0];if(!f)return;var done=function(text){var t=String(text||''),lines=t.split(/\r?\n/),x=V.CON;var m=t.match(/Contractor:\s*([^\n]+)/i);if(m)x.company=m[1].trim();m=t.match(/(?:Property )?Address:\s*([^\n]+)/i);if(m)x.property=m[1].trim();m=t.match(/Proposal No\.:\s*([^\n]+)/i);if(m)x.proposal=m[1].trim();var parsed=[];lines.forEach(function(line){var mm=line.match(/^(.{5,90}?)\s+\$?([\d,]+\.\d{2})\s+\$?([\d,]+\.\d{2})\s+\$?([\d,]+\.\d{2})\s*$/);if(mm)parsed.push({description:mm[1].trim(),labor:N(mm[2]),material:N(mm[3])});});if(parsed.length)x.rows=parsed;V.renderContractor();say('Estimate extracted','Review scope, labor, materials, and totals before syncing.');};if(/\.pdf$/i.test(f.name)&&window.pdfText)window.pdfText(f).then(function(r){done(r.text);});else f.text().then(done);};
function buildContractor(){if($('v14ConModal'))return;modal('v14ConModal','Contractor Estimate','<div id="v14ConBody"></div>');var f=document.createElement('input');f.id='v14ConFile';f.type='file';f.accept='.pdf,.txt';f.style.display='none';f.onchange=function(){V.conOCR(f.files);f.value='';};document.body.appendChild(f);V.renderContractor();}

/* Itemized fee sheet follows the provided LE labels and feeds supported closing overrides. */
V.FEES=[
 {sec:'A',name:'Origination Fee',map:'lenderOrigination',amount:0},{sec:'A',name:'Reno Admin Fee',map:'lenderProcessing',amount:0},
 {sec:'B',name:'Appraisal Fee',map:'appraisal',amount:0},{sec:'B',name:'Appraisal - Re-Inspection',map:'inspections',amount:0},{sec:'B',name:'Credit Report',map:'creditReport',amount:0},{sec:'B',name:'Flood Certification',map:'floodTaxService',amount:0},{sec:'B',name:'Reno Inspection Fee',reno:'inspectionFees',amount:0},{sec:'B',name:'Reno Title Update',reno:'titleUpdateFees',amount:0},{sec:'B',name:'Tax Service',map:'floodTaxService',amount:0},{sec:'B',name:'Verification Services',map:'other',amount:0},
 {sec:'C',name:'Title - Bankruptcy Search',map:'titleSearchSettlement',amount:0},{sec:'C',name:'Title - Endorsements',map:'titleInsurance',amount:0},{sec:'C',name:'Title - Escrow Fee',map:'titleSearchSettlement',amount:0},{sec:'C',name:"Title - Lender's Title Insurance",map:'titleInsurance',amount:0},{sec:'C',name:'Title - Municipal Lien Search',map:'titleSearchSettlement',amount:0},{sec:'C',name:'Title - Sales Tax',map:'titleSearchSettlement',amount:0},{sec:'C',name:'Title - Settlement Fee',map:'titleSearchSettlement',amount:0},{sec:'C',name:'Title - Attorney Fee',map:'attorney',amount:0},{sec:'C',name:'Title - Survey Inspection',map:'survey',amount:0},
 {sec:'E',name:'Recording Fees and Other Taxes',system:true,amount:0},{sec:'E',name:'Transfer Taxes',system:true,amount:0},
 {sec:'F',name:"Homeowner's Insurance Premium",system:true,amount:0},{sec:'F',name:'Prepaid Interest',system:true,amount:0},{sec:'F',name:'Property Taxes',system:true,amount:0},
 {sec:'G',name:"Homeowner's Insurance Escrow",system:true,amount:0},{sec:'G',name:'Property Taxes Escrow',system:true,amount:0},
 {sec:'H',name:'Escrow Holdback',system:true,amount:0},{sec:'H',name:"Title - Owner's Title Insurance (optional)",map:'titleInsurance',amount:0}
];
V.feeSet=function(i,v){V.FEES[i].amount=N(v);V.renderFees();};V.feeAdd=function(){V.FEES.push({sec:'H',name:'',map:'other',amount:0});V.renderFees();};V.feeName=function(i,v){V.FEES[i].name=v;};
V.pullFees=function(){var st=suite();if(!st)return;var o=st.outputs,lines=o.closing.lines||[];V.FEES.forEach(function(f){var exact=lines.filter(function(l){return l.label.toLowerCase()===f.name.toLowerCase();})[0];if(exact)f.amount=N(exact.amount);});function set(name,val){var f=V.FEES.filter(function(x){return x.name===name;})[0];if(f)f.amount=N(val);}set('Reno Inspection Fee',o.renovationOut.inspectionFees);set('Reno Title Update',o.renovationOut.titleUpdateFees);set('Prepaid Interest',o.closing.perDiemInterest);set('Escrow Holdback',o.renovationOut.rehabEscrowSubtotal);set('Recording Fees and Other Taxes',o.closing.mortgageRecordingTax);set('Property Taxes Escrow',o.escrowOut.initialEscrowDeposit);V.renderFees();say('Live fees loaded','Only values already calculated in the open scenario were copied.');};
V.syncFees=function(){var st=suite();if(!st)return;var sums={};V.FEES.forEach(function(f){if(f.map&&N(f.amount)>0)sums[f.map]=(sums[f.map]||0)+N(f.amount);});Object.keys(sums).forEach(function(k){st.setField('closing.overrides.'+k,sums[k],'Itemized fee sheet');});var reno={};V.FEES.forEach(function(f){if(f.reno&&N(f.amount)>0)reno[f.reno]=(reno[f.reno]||0)+N(f.amount);});Object.keys(reno).forEach(function(k){st.setField('reno.'+k,reno[k],'Itemized fee sheet');});var cp=$('v14CushionPct'),ri=$('v14Rounding');if(cp)st.setField('closing.cushionPct',N(cp.value)/100,'Itemized fee sheet');if(ri&&N(ri.value)>0)st.setField('closing.roundingIncrement',N(ri.value),'Itemized fee sheet');say('Itemized fees synced','Entered lender, title, appraisal, renovation, cushion, and rounding values now drive Closing and the draft LE.');};
V.renderFees=function(){var h=$('v14FeesBody');if(!h)return;var st=suite(),i=st&&st.activeInputs||{},sections=['A','B','C','E','F','G','H'],names={A:'Origination Charges',B:'Services You Cannot Shop For',C:'Services You Can Shop For',E:'Taxes and Other Government Fees',F:'Prepaids',G:'Initial Escrow Payment at Closing',H:'Other'},grand=0;h.innerHTML='<div class="v14-doc-inputs"><div class="v14-bar"><button class="btn btn-light" onclick="V14.pullFees()">Pull live closing and renovation fees</button><button class="btn btn-primary" onclick="V14.syncFees()">Fill Closing from itemized sheet</button><button class="btn btn-light" onclick="V14.feeAdd()">Add fee row</button><label>Cushion % <input class="cell-input" id="v14CushionPct" type="number" step="0.1" value="'+(N(i.closing&&i.closing.cushionPct)*100)+'"></label><label>Custom rounding <input class="cell-input" id="v14Rounding" type="number" min="1" value="'+(N(i.closing&&i.closing.roundingIncrement)||100)+'"></label></div><p class="muted small">System-calculated taxes, prepaids, and escrow stay controlled by their source fields to prevent double counting.</p></div><div class="v14-doc"><h1 style="text-align:left">Closing Cost Details</h1><div style="display:grid;grid-template-columns:1fr 1fr;gap:26px">'+sections.map(function(sec){var rows=V.FEES.map(function(f,j){return{f:f,i:j};}).filter(function(x){return x.f.sec===sec;});var sum=rows.reduce(function(a,x){return a+N(x.f.amount);},0);grand+=sum;return '<div><h2>'+sec+'. '+names[sec]+'</h2><table><tbody>'+rows.map(function(x){return '<tr><td><input class="cell-input" value="'+esc(x.f.name)+'" onchange="V14.feeName('+x.i+',this.value)"></td><td class="num"><input class="cell-input num" value="'+(x.f.amount||'')+'" onchange="V14.feeSet('+x.i+',this.value)"></td></tr>';}).join('')+'<tr class="total"><td>'+sec+'. Total</td><td class="num">'+money(sum)+'</td></tr></tbody></table></div>';}).join('')+'</div><table style="margin-top:24px"><tbody><tr class="grand"><td>J. TOTAL ITEMIZED COSTS</td><td class="num">'+money(grand)+'</td></tr></tbody></table></div>';};
function buildFees(){if($('v14FeesModal'))return;modal('v14FeesModal','Itemized Closing Fee Sheet','<div id="v14FeesBody"></div>');V.renderFees();}

/* Renovation cheat sheet applies the suite's existing fee assumptions on request. */
V.applyRenoEstimate=function(){var st=suite();if(!st)return;var i=st.activeInputs,o=st.outputs,draws=N(i.draws.drawCountOverride)||N(o.renovationOut.suggestedDrawCount)||1,units=N(i.units)||1,isFha=i.loanProgram==='FHA';var cont=units>1?.10:(i.reno.utilitiesOff?.15:.10);st.setField('reno.contingencyPct',cont,'Renovation fee guide');if(isFha&&!N(i.reno.consultant))st.setField('reno.consultant',2000,'Renovation fee guide');st.setField('draws.inspectionFeePerDraw',N(i.draws.inspectionFeePerDraw)||375,'Renovation fee guide');st.setField('draws.titleFeePerDraw',N(i.draws.titleFeePerDraw)||75,'Renovation fee guide');st.setField('draws.drawCountOverride',draws,'Renovation fee guide');st.setField('reno.syncDrawFees',true,'Renovation fee guide');say('Renovation fee estimate applied','The open scenario now uses its draw plan, property units, utilities status, and existing per-draw assumptions.');};
function enhanceRenoGuide(){var m=$('v13RenoModal');if(!m||m.__v14)return false;m.__v14=true;var b=m.querySelector('.v13-body');if(b)b.innerHTML='<div class="v14-bar no-print"><button class="btn btn-primary" onclick="V14.applyRenoEstimate()">Apply estimates to renovation suite</button><button class="btn btn-light" onclick="V14.open(\'v14FeesModal\')">Open itemized fee sheet</button></div><table class="v13-table" style="margin-top:14px"><thead><tr><th>Item</th><th>FHA 203(k)</th><th>HomeStyle</th></tr></thead><tbody><tr><td>Consultant fee</td><td>Use the entered/quoted 203(k) consultant fee.</td><td>Use only when the lender or scope requires it.</td></tr><tr><td>Contingency reserve</td><td>Use the suite assumption selected for utilities and scope.</td><td>10% required for 2–4 units; optional for one unit unless lender requires it; lender may increase to 15%.</td></tr><tr><td>Draw inspection</td><td colspan="2">Fee per draw × planned draws.</td></tr><tr><td>Title update</td><td colspan="2">Fee per draw × planned draws.</td></tr><tr><td>Supplemental origination</td><td>Calculated by the suite from eligible rehabilitation costs.</td><td>Use lender renovation administration fees actually entered.</td></tr><tr><td>Other actual costs</td><td colspan="2">Architect fees, permits, inspection/re-inspection, title updates, and escrow holdback flow from entered suite fields.</td></tr></tbody></table>';
  return true;}

function addLaunchers(){var tb=document.querySelector('#suite-root .toolbar');if(!tb||$('v14Launchers'))return false;var w=document.createElement('span');w.id='v14Launchers';w.className='v14-bar';w.innerHTML='<button class="btn ghost" onclick="V14.open(\'v14CompareModal\');V14.renderCompare()">Live Compare</button><button class="btn ghost" onclick="V14.open(\'v14FeesModal\')">Itemized Fees</button><button class="btn ghost" onclick="V14.open(\'v14ConModal\')">Contractor Estimate</button><button class="btn ghost" onclick="V14.open(\'v14LeaseModal\')">Lease</button><button class="btn ghost" onclick="V14.open(\'v14AddModal\')">Addendum</button>';tb.appendChild(w);return true;}
function addDocumentCard(){var h=$('subpanel-docs-paystub');if(!h||$('v14DocumentCard'))return false;var d=document.createElement('div');d.id='v14DocumentCard';d.className='card';d.innerHTML='<div class="card-top"><span class="tag">Generate</span><span class="doc-name">Documents</span></div><div class="card-body"><div class="v14-bar"><button class="btn btn-primary" onclick="V14.open(\'v13PlModal\')">Profit & Loss</button><button class="btn btn-light" onclick="V14.open(\'v14LeaseModal\')">Lease Agreement</button><button class="btn btn-light" onclick="V14.open(\'v14AddModal\')">Contract Addendum</button><button class="btn btn-light" onclick="V14.open(\'v14ConModal\')">Contractor Estimate</button><button class="btn btn-light" onclick="V14.open(\'v14FeesModal\')">Itemized Fee Sheet</button></div></div>';h.insertBefore(d,h.firstChild);return true;}
function addressFile(){if($('v14AddressFile'))return;var f=document.createElement('input');f.id='v14AddressFile';f.type='file';f.accept='.pdf,.txt';f.style.display='none';f.onchange=function(){V.addressOCR(f.files);f.value='';};document.body.appendChild(f);}
function boot(){buildCompare();buildLegalDocs();buildContractor();buildFees();addressFile();enhanceProperty();enhancePmi();enhancePL();enhancePaystub();enhanceRenoGuide();addThemeMenu();addLiveSummary();addPromptOptions();addLaunchers();addDocumentCard();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setInterval(function(){try{boot();V.renderLiveSummary();}catch(e){}},900);
})();
